/**
 * VFC Bank Router
 * Bank selection + one common upload pipeline only.
 * Bank-specific extraction/classification lives in Bank_<BANK>.gs.
 */
function vfcBankRegistry_(){return[vfcRbcBankProfile_(),vfcTdBankProfile_(),vfcScotiaBankProfile_(),vfcBmoBankProfile_(),vfcCibcBankProfile_(),vfcCoastCapitalBankProfile_()];}
function getBankParserTabs(){return vfcBankRegistry_().map(function(p){return{id:p.id,label:p.label,status:p.status,active:p.status==='LOCKED',rulesVersion:p.rulesVersion,intakeContract:VFC_BANK_ENGINE.INTAKE_CONTRACT};});}
function vfcGetBankProfile_(bankId){const id=String(bankId||'').toUpperCase().replace(/\s+/g,'_'),rows=vfcBankRegistry_();for(let i=0;i<rows.length;i++)if(rows[i].id===id)return rows[i];return{id:'UNKNOWN',label:'Unknown',status:'UNSUPPORTED',rulesVersion:'UNTRAINED',aliases:[]};}
function vfcDetectBankId_(text){
  const raw=String(text||'').trim(),s=raw.toUpperCase(),rows=vfcBankRegistry_();
  for(let i=0;i<rows.length;i++)if(s===rows[i].id||s===String(rows[i].label||'').toUpperCase())return rows[i].id;
  let bestId='UNKNOWN',bestScore=0;
  rows.forEach(function(p){(p.aliases||[]).forEach(function(alias){const a=String(alias||'').toUpperCase();if(!a||s.indexOf(a)<0)return;let score=a.length;if(a.length>=10||/BANK|ROYAL|MONTREAL|SCOTIA|IMPERIAL|COAST|DOMINION/.test(a))score+=100;if(score>bestScore){bestScore=score;bestId=p.id;}});});
  return bestId;
}
function vfcClassifyDebitForBank_(bankId,t){switch(String(bankId||'').toUpperCase()){case'RBC':return vfcRbcClassifyDebit_(t);case'TD':return vfcTdClassifyDebit_(t);case'SCOTIA':return vfcScotiaClassifyDebit_(t);case'BMO':return vfcBmoClassifyDebit_(t);case'CIBC':return vfcCibcClassifyDebit_(t);case'COAST_CAPITAL':return vfcCoastCapitalClassifyDebit_(t);default:return vfcGenericConservativeClassifyDebit_(t);}}
function vfcIsKnownFinancingCreditForBank_(bankId,t){switch(String(bankId||'').toUpperCase()){case'RBC':return vfcRbcKnownFinancingCredit_(t);case'TD':return vfcTdKnownFinancingCredit_(t);case'SCOTIA':return vfcScotiaKnownFinancingCredit_(t);case'BMO':return vfcBmoKnownFinancingCredit_(t);case'CIBC':return vfcCibcKnownFinancingCredit_(t);case'COAST_CAPITAL':return vfcCoastCapitalKnownFinancingCredit_(t);default:return false;}}
function vfcBankStrongEntityKey_(bankId,key,family){switch(String(bankId||'').toUpperCase()){case'RBC':return vfcRbcStrongEntityKey_(key);case'TD':return vfcTdStrongEntityKey_(key);case'BMO':return vfcBmoStrongEntityKey_(key);default:return false;}}
function vfcBankIsReturnedFinancingCredit_(bankId,t){switch(String(bankId||'').toUpperCase()){case'RBC':return vfcRbcIsReturnedFinancingCredit_(t);case'TD':return vfcTdIsReturnedFinancingCredit_(t);case'BMO':return vfcBmoIsReturnedFinancingCredit_(t);default:return false;}}
function vfcBankIsNonOperatingReversalCredit_(bankId,t){const id=String(bankId||'').toUpperCase();if(id==='BMO'&&typeof vfcBmoIsNonOperatingReversalCredit_==='function')return vfcBmoIsNonOperatingReversalCredit_(t);return vfcBankIsReturnedFinancingCredit_(id,t);}
function vfcBankIsNonOperatingTransferCredit_(bankId,t){switch(String(bankId||'').toUpperCase()){case'RBC':return vfcRbcIsNonOperatingTransferCredit_(t);case'TD':return vfcTdIsNonOperatingTransferCredit_(t);case'BMO':return vfcBmoIsNonOperatingTransferCredit_(t);default:return false;}}
function vfcBankPreservePrintedDuplicate_(bankId,t,occurrence,items){switch(String(bankId||'').toUpperCase()){case'RBC':return vfcRbcPreservePrintedDuplicate_(t,occurrence,items);case'BMO':return vfcBmoPreservePrintedDuplicate_(t,occurrence,items);default:return false;}}
function vfcBankExtractionRules_(bankId){switch(String(bankId||'').toUpperCase()){case'RBC':return vfcRbcExtractionRules_();case'TD':return vfcTdExtractionRules_();case'SCOTIA':return vfcScotiaExtractionRules_();case'BMO':return vfcBmoExtractionRules_();case'CIBC':return vfcCibcExtractionRules_();case'COAST_CAPITAL':return vfcCoastCapitalExtractionRules_();default:return'Extract conservatively. Do not infer missing transactions.';}}
function vfcLockBankStatementFacts_(bankId,summary,text,fileName){switch(String(bankId||'').toUpperCase()){case'RBC':return vfcRbcLockFacts_(summary,text,fileName);case'TD':return vfcTdLockFacts_(summary,text,fileName);case'SCOTIA':return vfcScotiaLockFacts_(summary,text,fileName);case'BMO':return vfcBmoLockFacts_(summary,text,fileName);case'CIBC':return vfcCibcLockFacts_(summary,text,fileName);case'COAST_CAPITAL':return vfcCoastCapitalLockFacts_(summary,text,fileName);default:return vfcLockPrintedStatementFacts_(summary,text);}}

function vfcNormalizeBankDocumentType_(value,summary){
  const s=String(value||'').trim().toUpperCase().replace(/[^A-Z0-9]+/g,'_');
  if(/^(NOT|NON)_?BANK/.test(s)||/NOT_BANK_STATEMENT|NON_BANK_STATEMENT/.test(s))return'NOT_BANK_STATEMENT';
  if((/BANK/.test(s)&&/STATEMENT/.test(s))||Array.isArray(summary&&summary.banking_transactions))return'BANK_STATEMENT';
  return'BANK_STATEMENT';
}
function vfcVerifyFrozenIntake_(raw,expectedBankId,fileName){return vfcValidateFrozenPayload_(raw,expectedBankId,fileName);}
function vfcCleanupStagedFiles_(staged){(staged||[]).forEach(function(item){try{if(item&&item.fileId)DriveApp.getFileById(item.fileId).setTrashed(true);}catch(e){}});}

/** Single approved upload entry point for every bank. */
function uploadStatementBatchByBank(bankId,companyName,files){
  const profile=vfcGetBankProfile_(bankId);if(profile.id==='UNKNOWN')throw new Error('Select a supported bank.');if(!companyName)throw new Error('Company name is required.');if(!files||!files.length)throw new Error('Upload at least one PDF.');
  const company=getOrCreateCompany_(companyName),companyFolder=DriveApp.getFolderById(company.folderId),tempFolder=getOrCreateSubFolder_(companyFolder,'_TEMP_PROCESSING'),staged=[];let rowsWritten=false;
  try{
    files.forEach(function(file){
      const fileName=file.name||'statement.pdf',blob=Utilities.newBlob(Utilities.base64Decode(file.base64),'application/pdf',fileName.toLowerCase().endsWith('.pdf')?fileName:fileName+'.pdf'),tempFile=tempFolder.createFile(blob),item={uploadId:Utilities.getUuid(),fileName:fileName,fileId:tempFile.getId(),fileUrl:tempFile.getUrl(),text:''};
      staged.push(item);item.text=extractTextFromPdf_(tempFile.getId());const detected=vfcDetectBankId_(item.text);if(detected!=='UNKNOWN'&&detected!==profile.id)throw new Error('Bank mismatch: '+fileName+' appears to be '+vfcGetBankProfile_(detected).label+', but '+profile.label+' was selected.');
    });
    const summaries=callOpenAIJsonBatch_(staged.map(function(item){return vfcBuildBankStatementPrompt_(profile,item.text,companyName,item.fileName);}));if(summaries.length!==staged.length)throw new Error(profile.label+' statement reader returned an incomplete batch.');
    const starts=[],ends=[];
    const processed=staged.map(function(item,index){
      let summary=summaries[index]||{};summary=vfcLockBankStatementFacts_(profile.id,summary,item.text,item.fileName)||summary;summary.bank_name=profile.label;summary.document_type=vfcNormalizeBankDocumentType_(summary.document_type,summary);
      if(summary.document_type==='NOT_BANK_STATEMENT')throw new Error(item.fileName+' was not recognized as a bank statement.');
      if(!Array.isArray(summary.banking_transactions))throw new Error('Banking ledger extraction was incomplete for '+item.fileName+'.');
      summary.possible_mca_or_loan_payments=vfcBankCreateIntakePayload_(summary,item.fileName);vfcVerifyFrozenIntake_(summary.possible_mca_or_loan_payments,profile.id,item.fileName);
      const startDate=parseDateSafe_(summary.statement_start_date),endDate=parseDateSafe_(summary.statement_end_date);if(startDate)starts.push(startDate);if(endDate)ends.push(endDate);
      return{uploadId:item.uploadId,fileName:item.fileName,fileId:item.fileId,fileUrl:item.fileUrl,summary:summary};
    });
    if(starts.length!==processed.length||ends.length!==processed.length)throw new Error(profile.label+' statement dates could not be verified for every uploaded statement.');
    const period=buildDetectedPeriod_(starts,ends),periodFolder=getOrCreateSubFolder_(companyFolder,period.label),uploadRows=[],pdfRows=[],batchInput=[],now=new Date();
    processed.forEach(function(item){uploadRows.push([item.uploadId,company.companyId,companyName,period.label,item.fileName,item.fileId,item.fileUrl,'READ',now]);pdfRows.push([item.uploadId,companyName,period.label,item.fileName,'BANK_STATEMENT',profile.label,item.summary.account_holder||'',item.summary.statement_start_date||'',item.summary.statement_end_date||'',item.summary.opening_balance||'',item.summary.closing_balance||'',item.summary.total_deposits||'',item.summary.total_withdrawals||'',item.summary.nsf_count||'',item.summary.negative_balance_detected||'',item.summary.possible_mca_or_loan_payments||'',item.summary.summary||'',item.summary.risks||'',item.summary.missing_info||'',now]);batchInput.push({fileName:item.fileName,summary:item.summary});});
    const batch=summarizeBatch_(batchInput,companyName,period.label);
    processed.forEach(function(item){const driveFile=DriveApp.getFileById(item.fileId);periodFolder.addFile(driveFile);tempFolder.removeFile(driveFile);});
    appendRows_('Uploads',uploadRows);appendRows_('PDF Summaries',pdfRows);appendRow_('Batch Summaries',[Utilities.getUuid(),companyName,period.label,files.length,period.earliest||'',period.latest||'',batch.combined_summary||'',batch.key_findings||'',batch.risks||'',batch.missing_info||'',new Date()]);rowsWritten=true;upsertStructuredFeature_(companyName,period.label);vfcFreezeDuplicateStatementFacts_(companyName,period.label);
    return{ok:true,intakeModelVersion:VFC_BANK_ENGINE.VERSION,intakeContract:VFC_BANK_ENGINE.INTAKE_CONTRACT,bankProfile:profile.id,bankRulesVersion:profile.rulesVersion,bankTrainingStatus:profile.status,companyName:companyName,detectedPeriod:period.label,filesUploaded:files.length,companyFolderLink:company.folderLink,periodFolderLink:periodFolder.getUrl(),batchSummary:batch};
  }catch(e){if(!rowsWritten)vfcCleanupStagedFiles_(staged);throw e;}
}

function vfcBuildBankStatementPrompt_(profile,text,companyName,fileName){return[
  'You are the VFC '+profile.label+' Bank Statement Fact Reader. Return JSON only.','Company: '+companyName,'File: '+fileName,'Selected bank profile: '+profile.id+' / '+profile.rulesVersion,
  'FACT EXTRACTION ONLY. Do not underwrite, estimate debt service, or infer frequency.',
  'Return fields: document_type, bank_name, account_holder, account_number, statement_start_date, statement_end_date, opening_balance, closing_balance, total_deposits, total_withdrawals, nsf_count, negative_balance_detected, banking_transactions, summary, risks, missing_info.',
  'For a valid bank statement set document_type exactly to BANK_STATEMENT.',
  'account_number must be the exact printed account number when clearly visible; otherwise return an empty string. Never invent or infer an account number.',
  'banking_transactions is an array of {date:"YYYY-MM-DD",description:"exact visible description",counterparty:"short counterparty",direction:"DEBIT" or "CREDIT",amount:number}.',
  'COMMON RULES:',
  '1. Header totals come from the printed statement summary, never by summing the transaction list.',
  '2. Printed debit/withdrawal versus credit/deposit columns control direction; wording never overrides the printed column.',
  '3. Preserve exact amounts, account identifiers and visible descriptions. Never borrow an amount or account number from an adjacent row.',
  '4. Do not duplicate cheque-image pages when the transaction already appears in account activity.',
  '5. Preserve every visible transaction required by the bank-specific rules, especially recurring-looking debits, financing/loan/MCA/PAD/advance/funding activity, loan interest, tax/government, insurance/premium finance, credit-card payments, equipment finance/lease payments and every required financing-credit candidate.',
  '6. Preserve original failed debits, returned/unpaid or reversal credits, and later retries as separate printed facts. Deterministic banking code decides which failed financing debit is excluded from recurring debt service.',
  '7. Extract incoming credits of $5,000 or more when they could plausibly be financing. Classification happens later.',
  '8. If a transaction row is visibly present but the counterparty is unclear, still extract the exact visible description when date, amount and debit/credit direction can be tied to that row. Omit only when the row cannot be reliably associated with its date, amount or direction.',
  '9. Never invent a missing transaction, amount, date, counterparty, account number or direction.',
  '10. Preserve unfamiliar named electronic debits even when the counterparty is not in any known lender/vendor rule. This includes PAD/pre-authorized/automatic payments, EFT/ACH, bill payments, misc payments, online banking payments and account-payable debits with a visible counterparty or reference. BankingCore may later identify recurrence across statements and surface the item as an informational obligation. Do not classify it as financing unless financing evidence is actually printed.',
  'BANK-SPECIFIC RULES:',vfcBankExtractionRules_(profile.id),'Document text:',String(text||'').substring(0,VFC_CONFIG.STATEMENT_TEXT_LIMIT)
].join('\n');}

function vfcFreezeDuplicateStatementFacts_(companyName,period){
  const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('PDF Summaries');if(!sh||sh.getLastRow()<2)return;const values=sh.getDataRange().getValues(),headers=values[0].map(vfcHeader_),idx={};headers.forEach(function(h,i){idx[h]=i;});const signalCol=idx[vfcHeader_('Possible MCA Or Loan Payments')];if(signalCol===undefined)return;function val(r,n){const i=idx[vfcHeader_(n)];return i===undefined?'':r[i];}const rows=[];
  for(let i=1;i<values.length;i++){const r=values[i];if(!vfcSame_(val(r,'Company Name'),companyName)||!vfcSame_(val(r,'Detected Period'),period))continue;rows.push({rowNumber:i+1,companyName:companyName,period:period,fileName:String(val(r,'File Name')||''),bank:String(val(r,'Bank Name')||''),accountHolder:String(val(r,'Account Holder')||''),startDate:val(r,'Statement Start Date'),endDate:val(r,'Statement End Date'),opening:vfcNumNull_(val(r,'Opening Balance')),closing:vfcNumNull_(val(r,'Closing Balance')),deposits:vfcNumNull_(val(r,'Total Deposits')),withdrawals:vfcNumNull_(val(r,'Total Withdrawals')),signalRaw:String(val(r,'Possible MCA Or Loan Payments')||''),createdAt:val(r,'Created At')});}
  vfcGroupLogicalStatementRows_(rows).forEach(function(group){const bankId=vfcDetectBankId_(group[0]&&group[0].bank||''),canonical=vfcCanonicalSignalRawFromRows_(group,bankId);if(!canonical)return;group.forEach(function(r){if(String(r.signalRaw||'')!==canonical)sh.getRange(r.rowNumber,signalCol+1).setValue(canonical);});});
}

function setupBankTrainingTabs(){const ss=SpreadsheetApp.getActiveSpreadsheet(),headers=['Bank','Training Status','Parser / Rules Version','Statement Format Notes','Debit Markers','Credit Markers','Financing Keywords','Recurring Payment Notes','Test Company','Test Period','Expected Gross Deposits','Expected Operating Deposits','Expected Monthly Debt','Expected Financing Credits','Last Validated','Notes'],created=[];vfcBankRegistry_().forEach(function(bank){const sheetName='BANK_'+bank.id;let sh=ss.getSheetByName(sheetName);if(!sh){sh=ss.insertSheet(sheetName);created.push(sheetName);}if(sh.getLastRow()===0){sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);sh.getRange(2,1,1,headers.length).setValues([[bank.label,bank.status,bank.rulesVersion,'','','','','','','','','','','','','']]);sh.autoResizeColumns(1,headers.length);}else{sh.getRange(2,1).setValue(bank.label);sh.getRange(2,2).setValue(bank.status);sh.getRange(2,3).setValue(bank.rulesVersion);}});return{ok:true,created:created,tabs:getBankParserTabs()};}

function runBankingStackSelfTests(){
  const router=[];function test(name,fn){try{router.push({name:name,pass:true,detail:String(fn()||'')});}catch(e){router.push({name:name,pass:false,detail:String(e&&e.message||e)});}}function equal(a,b,label){if(a!==b)throw new Error((label||'value')+' expected '+b+' but got '+a);}function close(a,b,t,label){if(Math.abs(Number(a||0)-Number(b||0))>(t==null?.02:t))throw new Error((label||'value')+' expected '+b+' but got '+a);}
  test('Router detects RBC from header even with other-bank words in transactions',function(){equal(vfcDetectBankId_('ROYAL BANK OF CANADA Account Summary TD VISA payment'),'RBC','RBC detection');return'RBC';});
  test('Router detects TD over incidental RBC loan wording',function(){equal(vfcDetectBankId_('THE TORONTO-DOMINION BANK TD Every Day B RBC LOAN PYMT LOAN'),'TD','TD detection');return'TD';});
  test('Router detects BMO',function(){equal(vfcDetectBankId_('BMO BANK OF MONTREAL Business Banking statement'),'BMO','BMO detection');return'BMO';});
  test('Current-rules ledger outranks legacy ledger and stays earliest within current generation',function(){const current=vfcTdBankProfile_().rulesVersion,prefix=VFC_BANK_ENGINE.CACHE_PREFIX,base={transactionsVerified:true,transactions:[],totalDeposits:100,totalWithdrawals:90,bankId:'TD',bankName:'TD'},legacy=prefix+JSON.stringify(Object.assign({},base,{fileName:'legacy'})),now1=prefix+JSON.stringify(Object.assign({},base,{fileName:'current-first',intakeContract:VFC_BANK_ENGINE.INTAKE_CONTRACT,bankRulesVersion:current})),now2=prefix+JSON.stringify(Object.assign({},base,{fileName:'current-second',intakeContract:VFC_BANK_ENGINE.INTAKE_CONTRACT,bankRulesVersion:current})),raw=vfcCanonicalSignalRawFromRows_([{bank:'TD',signalRaw:legacy,createdAt:'2025-01-01'},{bank:'TD',signalRaw:now1,createdAt:'2026-01-01'},{bank:'TD',signalRaw:now2,createdAt:'2026-02-01'}],'TD'),p=vfcParseBankCache_(raw);equal(p.fileName,'current-first','canonical current ledger');return p.fileName;});
  test('Corrected re-upload keeps one logical statement despite changed totals',function(){const current=vfcRbcBankProfile_().rulesVersion,prefix=VFC_BANK_ENGINE.CACHE_PREFIX,base={version:5,transactionsVerified:true,transactions:[],bankId:'RBC',bankName:'RBC',accountNumber:'03600 101-177-4',statementStartDate:'2026-01-22',statementEndDate:'2026-02-20',intakeContract:VFC_BANK_ENGINE.INTAKE_CONTRACT},oldRaw=prefix+JSON.stringify(Object.assign({},base,{bankRulesVersion:'RBC-OLD',fileName:'Jan-Feb.pdf',totalDeposits:19000,totalWithdrawals:28000})),newRaw=prefix+JSON.stringify(Object.assign({},base,{bankRulesVersion:current,fileName:'Jan-Feb.pdf',totalDeposits:20723.05,totalWithdrawals:29715.95})),oldRow={companyName:'TEST',period:'Jan to Jul',fileName:'Jan-Feb.pdf',bank:'RBC',startDate:'2026-01-22',endDate:'2026-02-20',deposits:19000,withdrawals:28000,signalRaw:oldRaw,createdAt:'2026-01-01'},newRow={companyName:'TEST',period:'Jan to Jul',fileName:'Jan-Feb.pdf',bank:'RBC',startDate:'2026-01-22',endDate:'2026-02-20',deposits:20723.05,withdrawals:29715.95,signalRaw:newRaw,createdAt:'2026-02-01'},groups=vfcGroupLogicalStatementRows_([oldRow,newRow]);equal(groups.length,1,'logical groups');const raw=vfcCanonicalSignalRawFromRows_(groups[0],'RBC'),p=vfcParseBankCache_(raw);close(p.totalDeposits,20723.05,.001,'corrected deposits');return'one identity, corrected deposits='+p.totalDeposits;});
  test('Legacy row without account number joins exactly one matching current account row',function(){const prefix=VFC_BANK_ENGINE.CACHE_PREFIX,base={transactionsVerified:true,transactions:[],totalDeposits:100,totalWithdrawals:90,bankId:'RBC',bankName:'RBC',statementStartDate:'2026-01-01',statementEndDate:'2026-01-31'},legacy={bank:'RBC',fileName:'January.pdf',startDate:'2026-01-01',endDate:'2026-01-31',signalRaw:prefix+JSON.stringify(Object.assign({},base,{fileName:'January.pdf'}))},current={bank:'RBC',fileName:'January.pdf',startDate:'2026-01-01',endDate:'2026-01-31',signalRaw:prefix+JSON.stringify(Object.assign({},base,{fileName:'January.pdf',accountNumber:'111-222'}))};equal(vfcGroupLogicalStatementRows_([legacy,current]).length,1,'mixed-generation group');return'joined safely';});
  test('Different known account numbers remain separate even with same filename and dates',function(){const prefix=VFC_BANK_ENGINE.CACHE_PREFIX,base={transactionsVerified:true,transactions:[],totalDeposits:100,totalWithdrawals:90,bankId:'RBC',bankName:'RBC',fileName:'statement.pdf',statementStartDate:'2026-01-01',statementEndDate:'2026-01-31'},a={bank:'RBC',fileName:'statement.pdf',startDate:'2026-01-01',endDate:'2026-01-31',signalRaw:prefix+JSON.stringify(Object.assign({},base,{accountNumber:'111-222'}))},b={bank:'RBC',fileName:'statement.pdf',startDate:'2026-01-01',endDate:'2026-01-31',signalRaw:prefix+JSON.stringify(Object.assign({},base,{accountNumber:'333-444'}))};equal(vfcGroupLogicalStatementRows_([a,b]).length,2,'account groups');return'separate';});
  test('Possible financing credit cannot be created from tax/card/other debit matching',function(){const credit={bankId:'RBC',date:'2026-01-05',description:'BRXM Payroll credit',counterparty:'BRXM Payroll',direction:'CREDIT',amount:10000},other={bankId:'RBC',date:'2026-01-06',description:'Business PAD BRXM Payroll',counterparty:'BRXM Payroll',direction:'DEBIT',amount:1000,family:'OTHER',entityKey:'RBC_OTHER_PAD_BRXM_PAYROLL'},f=vfcFinancingCredits_([credit],[other]);equal(f.possible.length,0,'possible financing');equal(f.confirmed.length,0,'confirmed financing');return'no false financing match';});
  test('BMO error correction is non-operating but not a financing-return marker',function(){const t={bankId:'BMO',date:'2026-02-03',description:'Error Correction, 0709-1985-790 0749',direction:'CREDIT',amount:5020.38};equal(vfcBankIsNonOperatingReversalCredit_('BMO',t),true,'non-operating reversal');equal(vfcBankIsReturnedFinancingCredit_('BMO',t),false,'financing return');return'separated';});
  const suites={RBC:runRbcBankingSelfTests(),TD:runTdBankingSelfTests(),BMO:runBmoBankingSelfTests()},routerFailed=router.filter(function(x){return!x.pass;}).length,suiteFailed=Object.keys(suites).reduce(function(n,k){return n+(suites[k].failed||0);},0),suiteTotal=Object.keys(suites).reduce(function(n,k){return n+(suites[k].total||0);},0),suitePassed=Object.keys(suites).reduce(function(n,k){return n+(suites[k].passed||0);},0);
  return{ok:routerFailed===0&&suiteFailed===0,coreVersion:VFC_BANK_ENGINE.VERSION,intakeContract:VFC_BANK_ENGINE.INTAKE_CONTRACT,total:router.length+suiteTotal,passed:(router.length-routerFailed)+suitePassed,failed:routerFailed+suiteFailed,routerTests:router,suites:suites};
}

function vfcGenericConservativeClassifyDebit_(t){const s=String(t.description||'').toUpperCase().replace(/\s+/g,' ').trim();if(/\bFEE\b|SERVICE\s+CHARGE|NSF|OVERDRAFT\s+INTEREST/.test(s))return null;if(/\bCRA\b|\bCCRA\b|GST|HST|\bTAX\b/.test(s)){const k=vfcCounterpartyKey_(t.counterparty||t.description);return Object.assign({},t,{family:'TAX',entityKey:k,key:k,label:t.counterparty||t.description});}if(/INSURANCE|PREMIUM\s+FIN/.test(s)){const k=vfcCounterpartyKey_(t.counterparty||t.description);return Object.assign({},t,{family:'OTHER',entityKey:k,key:k,label:t.counterparty||t.description});}if(/LOAN\s+(PAYMENT|PMT|PYMT|INTEREST)|\bMCA\b|MERCHANT\s+CASH\s+ADVANCE|FINANCING\s+PAYMENT/.test(s)){const k=vfcCounterpartyKey_(t.counterparty||t.description);return Object.assign({},t,{family:'FINANCING',entityKey:k,key:k,label:t.counterparty||t.description});}return null;}