/**
 * VFC Banking Core 3.5
 * Shared bank-agnostic banking math over frozen statement facts.
 * No PDF or OpenAI call occurs during underwriting.
 */
const VFC_BANK_ENGINE={
  VERSION:'VFC-BANKING-CORE-3.5',
  FACTS_VERSION:'VFC-BANK-FACTS-1.0',
  CACHE_PREFIX:'VFC_BANK_FACTS_V1:',
  LEGACY_PREFIXES:['VFC_BANK_PURE_V46:','VFC_BANK_PURE_V45:','VFC_BANK_PURE_V44:','VFC_BANK_PURE_V43:','VFC_BANK_PURE_V42:','VFC_BANK_PURE_V41:','VFC_BANK_PURE_V40:','VFC_BANK_PURE_V35:','VFC_BANK_PURE_V34:','VFC_BANK_PURE_V1:'],
  MAX_STATEMENTS:12,DEBT_LOOKBACK:6,ACTIVE_DAYS:75,RECONCILE_TOLERANCE:5
};
const VFC_BANK_SIMPLE=VFC_BANK_ENGINE;

function getBankingInputQualityStatus(){return{modelVersion:VFC_BANK_ENGINE.VERSION,factsVersion:VFC_BANK_ENGINE.FACTS_VERSION,deterministic:true,pdfReReadDuringUnderwriting:false,frozenStatementFacts:true,allRiskDrivingFeaturesFromFrozenFacts:true,architecture:'BankingCore + BankRouter + one isolated file per bank',banks:getBankParserTabs()};}

function vfcBankCreateIntakePayload_(summary,fileName){
  summary=summary||{};const opening=vfcNumNull_(summary.opening_balance),closing=vfcNumNull_(summary.closing_balance),deposits=vfcNumNull_(summary.total_deposits),withdrawals=vfcNumNull_(summary.total_withdrawals),diff=(opening!==null&&closing!==null&&deposits!==null&&withdrawals!==null)?vfcRound_((opening+deposits-withdrawals)-closing,.01):null,bankName=String(summary.bank_name||'Unknown');
  return VFC_BANK_ENGINE.CACHE_PREFIX+JSON.stringify({version:3,extractionVersion:VFC_BANK_ENGINE.FACTS_VERSION,fileName:String(fileName||''),bankId:vfcDetectBankId_(bankName),bankName:bankName,statementStartDate:vfcIso_(summary.statement_start_date),statementEndDate:vfcIso_(summary.statement_end_date),openingBalance:opening,closingBalance:closing,totalDeposits:deposits,totalWithdrawals:withdrawals,reconciliationDifference:diff,nsfCount:Math.max(0,vfcNum_(summary.nsf_count)),negativeBalanceDetected:vfcBool_(summary.negative_balance_detected),transactionsVerified:true,transactions:vfcNormalizeTransactions_(summary.banking_transactions||[])});
}

function getValidatedBankingFeatures_(companyName,period){
  const base=vfcBaseFeatures_(companyName,period);if(!base)return null;const rows=vfcSelectedStatementRows_(companyName,period);if(!rows.length)return base;const prepared=[],errors=[];
  rows.forEach(function(row){const payload=vfcCanonicalPayloadForRow_(row);if(!payload){errors.push(row.fileName+': no frozen transaction ledger found; re-upload this statement once.');return;}const check=vfcReconcilePayload_(payload,row);if(!check.ok){errors.push(row.fileName+': statement totals do not reconcile.');return;}prepared.push({row:row,payload:payload});});
  if(errors.length)throw new Error('Unable to verify uploaded bank statement(s): '+errors.join(' | '));return vfcBuildBankingFeatures_(base,prepared);
}

function refreshDebtSignalsForPeriodSafe(companyOrRequest,requestedPeriod){
  try{const req=vfcRequest_(companyOrRequest,requestedPeriod),period=req.period||(typeof resolveLatestAssessmentPeriod_==='function'?resolveLatestAssessmentPeriod_(req.companyName,req.period):req.period),f=getValidatedBankingFeatures_(req.companyName,period);if(!f)throw new Error('No banking features found.');return{ok:true,modelVersion:VFC_BANK_ENGINE.VERSION,resultFingerprint:f.resultFingerprint||'',companyName:req.companyName,period:period,bankTabs:getBankParserTabs(),debtProfile:f.debtProfile||{},inputQualityAudit:f.inputQualityAudit||{},bankingFeatures:{averageMonthlyDeposits:f.averageMonthlyDeposits||0,estimatedOperatingMonthlyDeposits:f.estimatedOperatingMonthlyDeposits||0,existingMonthlyDebtService:f.existingMonthlyDebtService||0,informationalRecurringMonthlyObligations:f.informationalRecurringMonthlyObligations||0,detectedFinancingCredits:f.detectedFinancingCredits||0},errors:[]};}
  catch(e){return{ok:false,modelVersion:VFC_BANK_ENGINE.VERSION,errors:[String(e&&e.message||e)]};}
}
function refreshLatestDebtSignals(){const rows=vfcSummaryRows_('','');if(!rows.length)throw new Error('No bank statements found.');rows.sort(function(a,b){return vfcTime_(a.createdAt)-vfcTime_(b.createdAt);});const last=rows[rows.length-1];return refreshDebtSignalsForPeriodSafe({companyName:last.companyName,period:last.period});}
function diagnoseLatestBankingInputs(){return refreshLatestDebtSignals();}

function vfcSummaryRows_(companyName,period){
  const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('PDF Summaries');if(!sh||sh.getLastRow()<2)return[];const values=sh.getDataRange().getValues(),headers=values[0].map(vfcHeader_),idx={};headers.forEach(function(h,i){idx[h]=i;});function val(r,n){const i=idx[vfcHeader_(n)];return i===undefined?'':r[i];}const out=[];
  for(let i=1;i<values.length;i++){const r=values[i],company=String(val(r,'Company Name')||'').trim(),detected=String(val(r,'Detected Period')||'').trim();if(companyName&&!vfcSame_(company,companyName))continue;if(period&&!vfcSame_(detected,period))continue;out.push({rowNumber:i+1,uploadId:String(val(r,'Upload ID')||'').trim(),companyName:company,period:detected,fileName:String(val(r,'File Name')||'').trim(),bank:String(val(r,'Bank Name')||'').trim(),startDate:val(r,'Statement Start Date'),endDate:val(r,'Statement End Date'),opening:vfcNumNull_(val(r,'Opening Balance')),closing:vfcNumNull_(val(r,'Closing Balance')),deposits:vfcNumNull_(val(r,'Total Deposits')),withdrawals:vfcNumNull_(val(r,'Total Withdrawals')),nsf:vfcNum_(val(r,'NSF Count')),negative:vfcBool_(val(r,'Negative Balance Detected')),signalRaw:String(val(r,'Possible MCA Or Loan Payments')||''),createdAt:val(r,'Created At')});}
  return out;
}
function vfcSelectedStatementRows_(companyName,period){const all=vfcSummaryRows_(companyName,period),map={};all.forEach(function(r){const key=vfcStatementFingerprint_(r),old=map[key];if(!old||vfcTime_(r.createdAt)>vfcTime_(old.createdAt))map[key]=r;});const rows=Object.keys(map).map(function(k){return map[k];});rows.sort(function(a,b){return vfcTime_(a.endDate)-vfcTime_(b.endDate)||String(a.fileName).localeCompare(String(b.fileName));});return rows.slice(Math.max(0,rows.length-VFC_BANK_ENGINE.MAX_STATEMENTS));}
function vfcStatementFingerprint_(r){return[String(r.bank||'').toUpperCase(),vfcIso_(r.startDate),vfcIso_(r.endDate),vfcRound_(vfcNum_(r.opening),.01),vfcRound_(vfcNum_(r.closing),.01),vfcRound_(vfcNum_(r.deposits),.01),vfcRound_(vfcNum_(r.withdrawals),.01)].join('|');}

/** The earliest verified ledger for an exact statement fingerprint is canonical forever. */
function vfcCanonicalPayloadForRow_(row){
  const fp=vfcStatementFingerprint_(row),pool=vfcSummaryRows_(row.companyName,row.period).filter(function(x){return vfcStatementFingerprint_(x)===fp;}).sort(function(a,b){return vfcTime_(a.createdAt)-vfcTime_(b.createdAt);});
  for(let i=0;i<pool.length;i++){const p=vfcParseBankCache_(pool[i].signalRaw);if(vfcPayloadUsable_(p))return vfcNormalizePayload_(p,row);}const exact=vfcParseBankCache_(row.signalRaw);return vfcPayloadUsable_(exact)?vfcNormalizePayload_(exact,row):null;
}
function vfcParseBankCache_(raw){const s=String(raw||''),prefixes=[VFC_BANK_ENGINE.CACHE_PREFIX].concat(VFC_BANK_ENGINE.LEGACY_PREFIXES);for(let i=0;i<prefixes.length;i++){if(s.indexOf(prefixes[i])!==0)continue;try{return JSON.parse(s.slice(prefixes[i].length));}catch(e){return null;}}return null;}
function vfcPayloadUsable_(p){return!!(p&&p.transactionsVerified&&Array.isArray(p.transactions)&&vfcNumNull_(p.totalDeposits)!==null&&vfcNumNull_(p.totalWithdrawals)!==null);}
function vfcNormalizePayload_(p,row){return{version:3,extractionVersion:VFC_BANK_ENGINE.FACTS_VERSION,fileName:String(p.fileName||row.fileName||''),bankId:String(p.bankId||vfcDetectBankId_(p.bankName||row.bank||'')),bankName:String(p.bankName||row.bank||'Unknown'),statementStartDate:vfcIso_(p.statementStartDate||row.startDate),statementEndDate:vfcIso_(p.statementEndDate||row.endDate),openingBalance:vfcNumNull_(p.openingBalance),closingBalance:vfcNumNull_(p.closingBalance),totalDeposits:vfcPos_(p.totalDeposits),totalWithdrawals:vfcPos_(p.totalWithdrawals),reconciliationDifference:vfcNum_(p.reconciliationDifference),nsfCount:Math.max(0,vfcNum_(p.nsfCount||row.nsf)),negativeBalanceDetected:!!(p.negativeBalanceDetected||row.negative),transactionsVerified:true,transactions:vfcNormalizeTransactions_(p.transactions||[])};}
function vfcReconcilePayload_(p,row){const opening=p.openingBalance!==null?p.openingBalance:row.opening,closing=p.closingBalance!==null?p.closingBalance:row.closing,deposits=p.totalDeposits,withdrawals=p.totalWithdrawals;if(opening===null||closing===null||deposits===null||withdrawals===null)return{ok:false};const diff=Math.abs((opening+deposits-withdrawals)-closing);return{ok:diff<=VFC_BANK_ENGINE.RECONCILE_TOLERANCE,diff:diff};}
function vfcNormalizeTransactions_(items){const out=[],seen={};(Array.isArray(items)?items:[]).forEach(function(x){const date=vfcIso_(x.date),desc=String(x.description||'').replace(/\s+/g,' ').trim(),direction=String(x.direction||'').toUpperCase(),amount=vfcPos_(x.amount);if(!date||!desc||(direction!=='DEBIT'&&direction!=='CREDIT')||!(amount>0))return;const t={date:date,description:desc.substring(0,220),counterparty:String(x.counterparty||desc).replace(/\s+/g,' ').trim().substring(0,140),direction:direction,amount:vfcRound_(amount,.01)},key=[t.date,t.direction,t.amount,t.description.toUpperCase()].join('|');if(!seen[key]){seen[key]=1;out.push(t);}});out.sort(function(a,b){return vfcTime_(a.date)-vfcTime_(b.date)||a.direction.localeCompare(b.direction)||a.amount-b.amount||a.description.localeCompare(b.description);});return out;}

/** Every field used by Our Max risk scoring is recalculated from deduplicated frozen statements. */
function vfcBuildBankingFeatures_(base,rows){
  let totalDeposits=0,totalWithdrawals=0,nsf=0,negative=0;const monthlyDeposits=[],monthlyWithdrawals=[],openings=[],closings=[],audit=[],allTx=[];
  rows.forEach(function(x){const p=x.payload;totalDeposits+=p.totalDeposits;totalWithdrawals+=p.totalWithdrawals;monthlyDeposits.push(p.totalDeposits);monthlyWithdrawals.push(p.totalWithdrawals);if(p.openingBalance!==null)openings.push(p.openingBalance);if(p.closingBalance!==null)closings.push(p.closingBalance);nsf+=p.nsfCount||0;if(p.negativeBalanceDetected)negative=1;(p.transactions||[]).forEach(function(t){allTx.push(Object.assign({bankId:p.bankId||'UNKNOWN'},t));});audit.push({fileName:x.row.fileName,bankId:p.bankId,bank:p.bankName,start:p.statementStartDate,end:p.statementEndDate,totalDeposits:p.totalDeposits,totalWithdrawals:p.totalWithdrawals,reconciliationDifference:p.reconciliationDifference,transactionsVerified:true,transactionCount:(p.transactions||[]).length});});
  const recent=rows.slice(Math.max(0,rows.length-VFC_BANK_ENGINE.DEBT_LOOKBACK)),debt=vfcDebtProfile_(recent),months=Math.max(1,rows.length),grossMonthly=totalDeposits/months,operatingTotal=Math.max(0,totalDeposits-debt.financingCreditsTotal-(debt.returnedCreditsTotal||0)),avgDep=vfcMean_(monthlyDeposits),txText=allTx.map(function(t){return String(t.description||'');}).join(' ').toUpperCase(),overdraftFlag=/OVERDRAFT|OVER LIMIT/.test(txText)?1:0,returnedFlag=allTx.some(function(t){return/RETURNED UNPAID|RETURNED ITEM|RETURNED PAYMENT|REVERSAL|CHARGEBACK|ITEM RETURNED NSF/.test(String(t.description||'').toUpperCase())||vfcBankIsReturnedFinancingCredit_(t.bankId||'UNKNOWN',t);})?1:0,stackingFlag=(debt.activeDebtObligations||[]).filter(function(x){return x.family==='MCA'||x.family==='PAD';}).length>=2?1:0,inputWarnings=(debt.warnings||[]).slice();
  audit.forEach(function(a){if((vfcNum_(a.totalDeposits)>0||vfcNum_(a.totalWithdrawals)>0)&&a.transactionCount===0)inputWarnings.push(a.fileName+': statement totals were present but no transaction rows were frozen; recurring-payment analysis may be incomplete.');});
  const result=Object.assign({},base,{statementCount:rows.length,monthsCovered:rows.length,totalDeposits:vfcRound_(totalDeposits,.01),averageMonthlyDeposits:vfcRound_(grossMonthly,.01),totalWithdrawals:vfcRound_(totalWithdrawals,.01),depositWithdrawalRatio:totalWithdrawals?vfcRound_(totalDeposits/totalWithdrawals,.01):0,averageOpeningBalance:vfcRound_(vfcMean_(openings),.01),averageClosingBalance:vfcRound_(vfcMean_(closings),.01),depositVolatility:vfcRound_(avgDep?vfcStdDev_(monthlyDeposits)/avgDep:1,.01),depositTrend:vfcRound_(vfcTrend_(monthlyDeposits),.01),nsfCount:nsf,nsfPerMonth:vfcRound_(nsf/months,.01),negativeBalanceFlag:negative,overdraftFlag:overdraftFlag,returnedPaymentFlag:returnedFlag,suspectedStacking:stackingFlag,missingInfoFlag:0,mcaPaymentFlag:debt.activeDebtObligations.length?1:0,monthlyDeposits:monthlyDeposits.slice(),monthlyWithdrawals:monthlyWithdrawals.slice(),estimatedOperatingTotalDeposits:vfcRound_(operatingTotal,.01),estimatedOperatingMonthlyDeposits:vfcRound_(operatingTotal/months,.01),detectedFinancingCredits:vfcRound_(debt.financingCreditsTotal,.01),existingMonthlyDebtService:vfcRound_(debt.confirmedMonthlyDebtService,.01),informationalRecurringMonthlyObligations:vfcRound_(debt.informationalMonthlyObligations,.01),otherRecurringMonthlyObligations:vfcRound_(debt.informationalMonthlyObligations,.01),debtServiceToDepositsRatio:grossMonthly?vfcRound_(debt.confirmedMonthlyDebtService/grossMonthly,.0001):0,debtProfile:debt,inputQualityAudit:{modelVersion:VFC_BANK_ENGINE.VERSION,verified:true,statementAudit:audit,warnings:inputWarnings}});
  result.resultFingerprint=vfcResultFingerprint_(result);result.inputQualityAudit.resultFingerprint=result.resultFingerprint;return result;
}

function vfcDebtProfile_(rows){
  let tx=[],latest='';rows.forEach(function(x){if(!latest||vfcTime_(x.payload.statementEndDate)>vfcTime_(latest))latest=x.payload.statementEndDate;(x.payload.transactions||[]).forEach(function(t){tx.push(Object.assign({bankId:x.payload.bankId||'UNKNOWN'},t));});});
  tx=vfcDedupeTx_(tx);const rawDebits=tx.filter(function(t){return t.direction==='DEBIT';}),credits=tx.filter(function(t){return t.direction==='CREDIT';}),returnedCredits=credits.filter(function(c){return vfcBankIsReturnedFinancingCredit_(c.bankId||'UNKNOWN',c);}),returnedCreditsTotal=returnedCredits.reduce(function(s,c){return s+vfcPos_(c.amount);},0),debits=vfcSuppressReturnedFinanceDebits_(rawDebits,credits),returnedFinanceDebitsSuppressed=Math.max(0,rawDebits.length-debits.length),classified=debits.map(function(t){return vfcClassifyDebitForBank_(t.bankId,t);}).filter(Boolean),groups={};
  classified.forEach(function(t){const key=t.bankId+'|'+t.family+'|'+t.entityKey;if(!groups[key])groups[key]={bankId:t.bankId,family:t.family,entityKey:t.entityKey,label:t.label,debtJustification:t.debtJustification||'',items:[]};if(!groups[key].debtJustification&&t.debtJustification)groups[key].debtJustification=t.debtJustification;groups[key].items.push(t);});
  let summaries=Object.keys(groups).sort().map(function(k){return vfcSummarizeGroup_(groups[k],latest);}).filter(Boolean);summaries=vfcMergeGenericAmountMatches_(summaries);
  const sweepByBank={};credits.forEach(function(c){if(/\bLOAN\s+CREDIT\b/i.test(c.description))sweepByBank[c.bankId]=(sweepByBank[c.bankId]||0)+1;});const active=[],revolving=[],tax=[],other=[],inactive=[],once=[];
  summaries.forEach(function(g){if((sweepByBank[g.bankId]||0)>=2&&g.entityKey==='GENERIC_LOAN_PAYMENT'){revolving.push(g);return;}if(!g.recurring){once.push(g);return;}if(g.family==='FINANCING'||g.family==='MCA'||g.family==='PAD'){if(g.active)active.push(g);else once.push(g);}else if(g.family==='TAX'){if(g.active)tax.push(g);else inactive.push(g);}else{if(g.active)other.push(g);else inactive.push(g);}});
  const financing=vfcFinancingCredits_(credits,classified);active.sort(vfcObligationSort_);tax.sort(vfcObligationSort_);other.sort(vfcObligationSort_);const confirmed=active.reduce(function(s,x){return s+x.monthlyEquivalent;},0),info=tax.concat(other).reduce(function(s,x){return s+x.monthlyEquivalent;},0),warnings=[];
  if(revolving.length)warnings.push('Generic revolving loan sweep activity is excluded from fixed monthly debt.');if(returnedFinanceDebitsSuppressed)warnings.push(returnedFinanceDebitsSuppressed+' returned/reversed financing debit'+(returnedFinanceDebitsSuppressed===1?' was':'s were')+' excluded from recurring debt service while the return event remains a risk fact.');if(returnedCreditsTotal)warnings.push('Returned/reversal credit activity of $'+vfcRound_(returnedCreditsTotal,.01)+' is excluded from estimated operating deposits.');if(inactive.length)warnings.push('Stale informational obligations are retained without a fabricated monthly equivalent.');if(financing.possible.length)warnings.push('Possible financing credits are shown separately and are not removed from operating deposits unless confirmed.');
  return{confirmedMonthlyDebtService:vfcRound_(confirmed,.01),informationalMonthlyObligations:vfcRound_(info,.01),activeDebtObligations:active,revolvingFinancingActivity:revolving,taxGovernmentPads:tax,otherRecurringObligations:other,inactiveInformationalObligations:inactive,observedOnce:once,allDetectedObligations:summaries,financingCredits:financing.confirmed,possibleFinancingCredits:financing.possible,financingCreditsTotal:vfcRound_(financing.total,.01),returnedCredits:returnedCredits,returnedCreditsTotal:vfcRound_(returnedCreditsTotal,.01),returnedFinanceDebitsSuppressed:returnedFinanceDebitsSuppressed,warnings:warnings};
}

/** Suppress a financing debit only when a same-amount return/reversal can be tied to it without ambiguity. */
function vfcSuppressReturnedFinanceDebits_(debits,credits){
  const returned=(credits||[]).filter(function(c){return /ITEM\s+RETURNED\s+NSF|RETURNED\s+ITEM|RETURNED\s+PAYMENT|RETURNED\s+UNPAID|REVERSAL/.test(String(c.description||'').toUpperCase())||vfcBankIsReturnedFinancingCredit_(c.bankId||'UNKNOWN',c);}),suppressed={};
  returned.forEach(function(c){const candidates=[];(debits||[]).forEach(function(d,i){if(suppressed[i])return;if(String(d.bankId||'')!==String(c.bankId||''))return;if(Math.abs(vfcNum_(d.amount)-vfcNum_(c.amount))>.01)return;const dd=vfcDate_(d.date),cd=vfcDate_(c.date);if(!dd||!cd)return;const days=(cd-dd)/86400000;if(days<0||days>3)return;const x=vfcClassifyDebitForBank_(d.bankId,d);if(!x||(x.family!=='FINANCING'&&x.family!=='MCA'))return;candidates.push({index:i,days:days,debit:d,classified:x});});
    if(!candidates.length)return;const minDays=Math.min.apply(null,candidates.map(function(x){return x.days;})),nearest=candidates.filter(function(x){return Math.abs(x.days-minDays)<.000001;});if(nearest.length===1){suppressed[nearest[0].index]=1;return;}
    const generic={ITEM:1,RETURNED:1,NSF:1,PAYMENT:1,REVERSAL:1,UNPAID:1,CREDIT:1,DEBIT:1};const ct=vfcTokens_(c.counterparty||c.description).filter(function(x){return!generic[x];});if(!ct.length)return;const scored=nearest.map(function(x){const dt=vfcTokens_(x.debit.counterparty||x.debit.description);let score=0;ct.forEach(function(a){if(dt.indexOf(a)>=0)score++;});return{index:x.index,score:score};}).sort(function(a,b){return b.score-a.score||a.index-b.index;});if(scored.length&&scored[0].score>0&&(scored.length===1||scored[0].score>scored[1].score))suppressed[scored[0].index]=1;
  });
  return(debits||[]).filter(function(d,i){return!suppressed[i];});
}

function vfcSummarizeGroup_(g,latestEnd){
  const items=(g.items||[]).slice().sort(function(a,b){return vfcTime_(a.date)-vfcTime_(b.date);});if(!items.length)return null;const amounts=items.map(function(x){return x.amount;}),months={};items.forEach(function(x){const m=x.date.slice(0,7);months[m]=(months[m]||0)+x.amount;});const distinct=Object.keys(months).length,occ=items.length,gaps=[];for(let i=1;i<items.length;i++)gaps.push((vfcDate_(items[i].date)-vfcDate_(items[i-1].date))/86400000);const medianGap=gaps.length?vfcMedian_(gaps):0,median=vfcMedian_(amounts),cv=vfcCv_(amounts),weeklyRatio=gaps.length?gaps.filter(function(x){return x>=5&&x<=10;}).length/gaps.length:0,biweeklyRatio=gaps.length?gaps.filter(function(x){return x>10&&x<=18;}).length/gaps.length:0,recurring=distinct>=2||occ>=3,daysSince=vfcDays_(items[items.length-1].date,latestEnd),active=daysSince===null?true:daysSince<=VFC_BANK_ENGINE.ACTIVE_DAYS;let frequency='Observed statement-period cash flow',monthly=0,method='OBSERVED_ONLY';
  if(recurring&&medianGap>=5&&medianGap<=10&&occ>=4&&weeklyRatio>=.65){frequency='Weekly observed cadence';monthly=median*52/12;method='WEEKLY_MEDIAN';}else if(recurring&&medianGap>10&&medianGap<=18&&occ>=3&&biweeklyRatio>=.55){frequency='Biweekly observed cadence';monthly=median*26/12;method='BIWEEKLY_MEDIAN';}else if(recurring&&distinct>=2&&occ===distinct){frequency='Monthly observed cadence';monthly=cv<=.03?median:vfcMeanObject_(months);method=cv<=.03?'MONTHLY_MEDIAN':'MONTHLY_VARIABLE_MEAN';}else if(recurring){frequency='Multiple payments per month';monthly=vfcRecentMonthAverage_(months,3);method='RECENT_3_MONTH_AVERAGE';}
  if(!active&&g.family!=='FINANCING'&&g.family!=='MCA'&&g.family!=='PAD'){monthly=0;method='STALE_INFORMATIONAL';}
  let why=String(g.debtJustification||'').trim();if(why&&recurring)why+=' Recurrence evidence: '+occ+' observed payment'+(occ===1?'':'s')+' across '+distinct+' month'+(distinct===1?'':'s')+'; '+frequency+'.';
  return{bankId:g.bankId||'',family:g.family,key:g.entityKey,entityKey:g.entityKey,counterparty:g.label,description:g.label,category:g.family==='FINANCING'?'LOAN':g.family,paymentAmount:vfcRound_(median,.01),averagePayment:vfcRound_(vfcMean_(amounts),.01),frequency:frequency,monthlyEquivalent:vfcRound_(monthly,.01),monthlyEquivalentMethod:method,occurrences:occ,distinctMonths:distinct,firstSeen:items[0].date,lastSeen:items[items.length-1].date,daysSinceLastObserved:daysSince,active:active,recurring:recurring,confidence:!recurring?'Low':(distinct>=3?'High':'Moderate'),observedTotal:vfcRound_(vfcSum_(amounts),.01),observedMonthlyTotals:vfcSortedMoneyObject_(months),components:vfcAmountComponents_(items),debtJustification:why};
}

function vfcAmountComponents_(items){
  const clusters=[];(items||[]).slice().sort(function(a,b){return a.amount-b.amount;}).forEach(function(item){let best=null,bestDiff=Infinity;clusters.forEach(function(c){const center=vfcMedian_(c.map(function(x){return x.amount;})),tolerance=Math.max(12,center*(center<2000?.15:.065)),diff=Math.abs(item.amount-center);if(diff<=tolerance&&diff<bestDiff){best=c;bestDiff=diff;}});if(best)best.push(item);else clusters.push([item]);});
  return clusters.map(function(c,i){const a=c.map(function(x){return x.amount;}),m={};c.forEach(function(x){m[x.date.slice(0,7)]=1;});return{componentId:'C'+(i+1),representativeAmount:vfcRound_(vfcMedian_(a),.01),averageAmount:vfcRound_(vfcMean_(a),.01),minAmount:vfcRound_(Math.min.apply(null,a),.01),maxAmount:vfcRound_(Math.max.apply(null,a),.01),occurrences:a.length,distinctMonths:Object.keys(m).length};}).sort(function(a,b){return a.representativeAmount-b.representativeAmount;});
}

function vfcMergeGenericAmountMatches_(groups){
  const out=[];(groups||[]).forEach(function(g){if(vfcIsStrongEntityKey_(g.entityKey,g.family,g.bankId)){out.push(g);return;}let target=null;out.some(function(e){if(String(e.bankId||'')!==String(g.bankId||''))return false;if(vfcIsStrongEntityKey_(e.entityKey,e.family,e.bankId)||e.family!==g.family||e.frequency!==g.frequency)return false;const tolerance=Math.max(8,Math.min(e.paymentAmount,g.paymentAmount)*.02),em=Object.keys(e.observedMonthlyTotals||{}),gm=Object.keys(g.observedMonthlyTotals||{}),overlap=em.filter(function(m){return gm.indexOf(m)>=0;}).length/Math.max(1,Math.min(em.length,gm.length));if(Math.abs(e.paymentAmount-g.paymentAmount)<=tolerance&&Math.min(e.distinctMonths,g.distinctMonths)>=2&&overlap<=.20){target=e;return true;}return false;});if(!target){out.push(g);return;}target.description=target.description+' / '+g.description;target.counterparty=target.description;target.observedTotal=vfcRound_(target.observedTotal+g.observedTotal,.01);target.occurrences+=g.occurrences;target.confidence='High';target.mergedByAmountCadence=true;});return out;
}

function vfcFinancingCredits_(credits,debits){const confirmed=[],possible=[];(credits||[]).forEach(function(c){if(vfcBankIsReturnedFinancingCredit_(c.bankId||'UNKNOWN',c))return;const s=String(c.description||'').toUpperCase(),amount=vfcPos_(c.amount);if(!(amount>0))return;const explicit=/\bLOAN\s+CREDIT\b|LOAN\s+ADVANCE|LOAN\s+PROCEEDS|FINANC(?:E|ING)\s+ADVANCE|FINANC(?:E|ING)\s+PROCEEDS|FUNDING\s+ADVANCE|MCA\s+ADVANCE|CSBFL\s+(?:LOAN\s+)?ADVANCE|CSBFL\s+PROCEEDS|MORTGAGE\s+(?:ADVANCE|PROCEEDS|FUNDING)|(?:\bLOC\b|LINE\s+OF\s+CREDIT|CREDIT\s+LINE)\s+(?:ADVANCE|PROCEEDS|FUNDING)/.test(s),matched=vfcMatchedPaymentEntity_(c,debits),known=vfcIsKnownFinancingCreditForBank_(c.bankId||'UNKNOWN',c),item={date:c.date,description:c.description,counterparty:c.counterparty,amount:c.amount,direction:'CREDIT',linkedPaymentEntity:matched,confidence:(explicit||known||matched)?'High':'Moderate'};if(explicit||(amount>=5000&&known))confirmed.push(item);else if(amount>=5000&&(matched||/INVESTMENT|CAPITAL/.test(s)))possible.push(item);});const c=vfcDedupeTx_(confirmed),p=vfcDedupeTx_(possible);return{confirmed:c,possible:p,total:c.reduce(function(s,x){return s+x.amount;},0)};}
function vfcMatchedPaymentEntity_(credit,debits){const ct=vfcTokens_(credit.counterparty||credit.description);if(!ct.length)return'';let found='';(debits||[]).some(function(d){const dt=vfcTokens_(d.counterparty||d.description);if(!dt.length)return false;let n=0;ct.forEach(function(a){if(dt.some(function(b){return a===b||(a.length>=4&&b.length>=4&&(a.indexOf(b)===0||b.indexOf(a)===0));}))n++;});if(n/Math.min(ct.length,dt.length)>=.5){found=d.entityKey||d.key||'';return true;}return false;});return found;}

function lockBankRegressionBaseline(companyName,period,bankId){bankId=String(bankId||'RBC').toUpperCase();const result=refreshDebtSignalsForPeriodSafe({companyName:companyName,period:period});if(!result.ok)throw new Error((result.errors||[]).join(' | '));const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName('BANK_REGRESSION_LOCKS');if(!sh){sh=ss.insertSheet('BANK_REGRESSION_LOCKS');sh.appendRow(['Company Name','Period','Bank','Result Fingerprint','Gross Monthly Deposits','Operating Monthly Deposits','Confirmed Monthly Debt','Financing Credits','Core Version','Locked At']);sh.setFrozenRows(1);}const values=sh.getDataRange().getValues();let rowNum=0;for(let i=1;i<values.length;i++)if(vfcSame_(values[i][0],companyName)&&vfcSame_(values[i][1],period)&&vfcSame_(values[i][2],bankId)){rowNum=i+1;break;}const b=result.bankingFeatures||{},row=[companyName,period,bankId,result.resultFingerprint,b.averageMonthlyDeposits||0,b.estimatedOperatingMonthlyDeposits||0,b.existingMonthlyDebtService||0,b.detectedFinancingCredits||0,VFC_BANK_ENGINE.VERSION,new Date()];if(rowNum)sh.getRange(rowNum,1,1,row.length).setValues([row]);else sh.appendRow(row);return{ok:true,locked:true,resultFingerprint:result.resultFingerprint};}
function verifyBankRegressionBaseline(companyName,period,bankId){bankId=String(bankId||'RBC').toUpperCase();const result=refreshDebtSignalsForPeriodSafe({companyName:companyName,period:period});if(!result.ok)return result;const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('BANK_REGRESSION_LOCKS');if(!sh||sh.getLastRow()<2)return{ok:false,error:'No regression baseline is locked.'};const values=sh.getDataRange().getValues();for(let i=1;i<values.length;i++)if(vfcSame_(values[i][0],companyName)&&vfcSame_(values[i][1],period)&&vfcSame_(values[i][2],bankId)){const expected=String(values[i][3]||'');return{ok:true,match:expected===result.resultFingerprint,expectedFingerprint:expected,actualFingerprint:result.resultFingerprint};}return{ok:false,error:'No matching regression baseline is locked.'};}
function vfcResultFingerprint_(f){const d=f.debtProfile||{},canonical={statementCount:f.statementCount||0,totalDeposits:vfcRound_(f.totalDeposits||0,.01),averageMonthlyDeposits:vfcRound_(f.averageMonthlyDeposits||0,.01),estimatedOperatingMonthlyDeposits:vfcRound_(f.estimatedOperatingMonthlyDeposits||0,.01),detectedFinancingCredits:vfcRound_(f.detectedFinancingCredits||0,.01),existingMonthlyDebtService:vfcRound_(f.existingMonthlyDebtService||0,.01),nsfPerMonth:vfcRound_(f.nsfPerMonth||0,.01),negativeBalanceFlag:f.negativeBalanceFlag||0,overdraftFlag:f.overdraftFlag||0,returnedPaymentFlag:f.returnedPaymentFlag||0,suspectedStacking:f.suspectedStacking||0,depositTrend:vfcRound_(f.depositTrend||0,.01),depositVolatility:vfcRound_(f.depositVolatility||0,.01),debt:(d.activeDebtObligations||[]).map(function(x){return[x.bankId||'',x.entityKey,x.monthlyEquivalent,x.frequency,x.paymentAmount,x.lastSeen];}),revolving:(d.revolvingFinancingActivity||[]).map(function(x){return[x.bankId||'',x.entityKey,x.monthlyEquivalent,x.frequency,x.paymentAmount,x.lastSeen];}),info:(d.otherRecurringObligations||[]).map(function(x){return[x.bankId||'',x.entityKey,x.monthlyEquivalent,x.frequency,x.paymentAmount,x.lastSeen];}),financing:(d.financingCredits||[]).map(function(x){return[x.date,x.amount,x.description];}),possibleFinancing:(d.possibleFinancingCredits||[]).map(function(x){return[x.date,x.amount,x.description];})};return vfcDigest_(JSON.stringify(canonical));}

function vfcBaseFeatures_(companyName,period){if(typeof buildPowerFeatures_==='function')return buildPowerFeatures_(companyName,period);if(typeof buildFeaturesForCase_==='function')return buildFeaturesForCase_(companyName,period);return null;}
function vfcRequest_(a,p){return a&&typeof a==='object'?{companyName:String(a.companyName||'').trim(),period:String(a.period||p||'').trim()}:{companyName:String(a||'').trim(),period:String(p||'').trim()};}
function vfcHeader_(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'');}
function vfcSame_(a,b){return String(a||'').trim().toLowerCase()===String(b||'').trim().toLowerCase();}
function vfcNum_(v){const n=Number(String(v==null?'':v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0;}
function vfcNumNull_(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null;}
function vfcPos_(v){return Math.max(0,vfcNum_(v));}
function vfcBool_(v){return/^(true|yes|y|1)$/i.test(String(v||'').trim())||/negative/i.test(String(v||''));}
function vfcRound_(v,step){step=step||.01;return Math.round((v+Number.EPSILON)/step)*step;}
function vfcDate_(v){if(!v)return null;const d=v instanceof Date?v:new Date(v);return isNaN(d.getTime())?null:d;}
function vfcIso_(v){const d=vfcDate_(v);if(!d)return/^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?String(v):'';return Utilities.formatDate(d,Session.getScriptTimeZone()||'GMT','yyyy-MM-dd');}
function vfcTime_(v){const d=vfcDate_(v);return d?d.getTime():0;}
function vfcSum_(a){return(a||[]).reduce(function(s,x){return s+vfcNum_(x);},0);}
function vfcMean_(a){return a&&a.length?vfcSum_(a)/a.length:0;}
function vfcMedian_(a){const x=(a||[]).slice().sort(function(m,n){return m-n;});if(!x.length)return 0;const k=Math.floor(x.length/2);return x.length%2?x[k]:(x[k-1]+x[k])/2;}
function vfcStdDev_(a){if(!a||!a.length)return 0;const m=vfcMean_(a);return Math.sqrt(a.reduce(function(s,x){return s+Math.pow(x-m,2);},0)/a.length);}
function vfcCv_(a){const m=vfcMean_(a);return m?vfcStdDev_(a)/m:0;}
function vfcTrend_(a){if(!a||a.length<2)return 0;const first=a[0],last=a[a.length-1],den=Math.max(Math.abs(first),1);return(last-first)/den;}
function vfcDays_(a,b){const da=vfcDate_(a),db=vfcDate_(b);return!da||!db?null:Math.max(0,Math.round((db-da)/86400000));}
function vfcMeanObject_(o){const k=Object.keys(o||{});return k.length?k.reduce(function(s,x){return s+vfcNum_(o[x]);},0)/k.length:0;}
function vfcRecentMonthAverage_(o,n){const k=Object.keys(o||{}).sort().slice(-Math.max(1,n||3));return k.length?k.reduce(function(s,x){return s+vfcNum_(o[x]);},0)/k.length:0;}
function vfcSortedMoneyObject_(o){const out={};Object.keys(o||{}).sort().forEach(function(k){out[k]=vfcRound_(o[k],.01);});return out;}
function vfcObligationSort_(a,b){return(b.monthlyEquivalent||0)-(a.monthlyEquivalent||0)||String(a.counterparty||'').localeCompare(String(b.counterparty||''));}
function vfcDedupeTx_(a){const out=[],seen={};(a||[]).forEach(function(t){const k=[t.bankId||'',t.date,t.direction,t.amount,String(t.description||'').toUpperCase()].join('|');if(!seen[k]){seen[k]=1;out.push(t);}});return out;}
function vfcTokens_(s){const stop={BUSINESS:1,INVESTMENT:1,PAD:1,PAYMENT:1,LOAN:1,CREDIT:1,DEBIT:1,THE:1,INC:1,LTD:1,CORP:1,CORPORATION:1,COMPANY:1,'001':1};return String(s||'').toUpperCase().replace(/[^A-Z0-9 ]/g,' ').split(/\s+/).filter(function(x){return x.length>=3&&!stop[x]&&!/^\d+$/.test(x);});}
function vfcCounterpartyKey_(s){const t=vfcTokens_(s);return t.slice(0,4).join('_')||String(s||'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').slice(0,60);}
function vfcIsStrongEntityKey_(key,family,bankId){const k=String(key||'').toUpperCase();return/^LOAN(_INTEREST)?_[0-9]/.test(k)||/^INSURANCE_/.test(k)||vfcBankStrongEntityKey_(bankId,k,family);}
function vfcDigest_(s){const bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s||''),Utilities.Charset.UTF_8);return bytes.map(function(b){const v=(b<0?b+256:b).toString(16);return v.length===1?'0'+v:v;}).join('').substring(0,24);}
