const VFC_BANKING_INPUT_CONFIG={MODEL_VERSION:'VFC-BANKING-INPUT-QUALITY-8.1-TD-ANCHOR-RECONCILIATION',SIGNAL_PREFIX:'VFC_BANKING_V11:',LEGACY_PREFIXES:['VFC_BANKING_V11:','VFC_BANKING_V10:','VFC_BANKING_V9:'],PAYLOAD_VERSION:11,MAX_STATEMENTS:12,DEBT_LOOKBACK_STATEMENTS:6,MAX_STATEMENT_GAP_DAYS:75,LATEST_BATCH_GAP_MINUTES:10,ACTIVE_LOOKBACK_DAYS:90,RECONCILE_TOLERANCE_DOLLARS:5};

function refreshDebtSignalsForPeriodSafe(companyOrRequest,requestedPeriod){try{const r=vfcBiqNormalizeRequest_(companyOrRequest,requestedPeriod);const p=r.period||(typeof resolveLatestAssessmentPeriod_==='function'?resolveLatestAssessmentPeriod_(r.companyName,r.period):r.period);return vfcBiqRefresh_(r.companyName,p);}catch(e){return{ok:false,modelVersion:VFC_BANKING_INPUT_CONFIG.MODEL_VERSION,filesAnalyzed:0,filesReused:0,filesSkipped:0,errors:[String(e&&e.message||e)]};}}
function refreshLatestDebtSignals(){const rows=vfcBiqReadSummaryRows_('','');if(!rows.length)throw new Error('PDF Summaries has no records.');const x=rows[rows.length-1];const r=refreshDebtSignalsForPeriodSafe({companyName:x.companyName,period:x.detectedPeriod});console.log(JSON.stringify(r,null,2));return r;}
function diagnoseLatestBankingInputs(){return refreshLatestDebtSignals();}
function getBankingInputQualityStatus(){const r={modelVersion:VFC_BANKING_INPUT_CONFIG.MODEL_VERSION,bankAgnostic:true,deterministicAdapters:['TD'],selfHealsUnverifiedStatements:true,partialStatementCalculationAllowed:false,lenderAgnosticRecurringPaymentDetection:true,excludesFeesFromDebt:true,separatesTaxInsuranceAndCards:true,changesProductionFormula:false};console.log(JSON.stringify(r,null,2));return r;}

function getValidatedBankingFeatures_(companyName,period){const base=typeof buildPowerFeatures_==='function'?buildPowerFeatures_(companyName,period):(typeof buildFeaturesForCase_==='function'?buildFeaturesForCase_(companyName,period):null);if(!base)return null;let a=vfcBiqBuildAudit_(companyName,period);if(!a.rows.length||a.processedRows===0)return base;if(!a.allStatementsVerified||a.processedRows!==a.rows.length){vfcBiqRepairUnverified_(companyName,period,a.rows);a=vfcBiqBuildAudit_(companyName,period);}if(!a.allStatementsVerified||a.processedRows!==a.rows.length)throw new Error('Banking input validation is incomplete after automatic repair: '+a.processedRows+' of '+a.rows.length+' statements verified.'+(a.unverifiedFiles.length?' Unverified: '+a.unverifiedFiles.join(', '):''));const d=vfcBiqBuildDebtProfile_(a.rows,a.monthsCovered,a.latestStatementDate);const gross=a.totalDeposits/Math.max(1,a.monthsCovered),operTotal=Math.max(0,a.totalDeposits-d.financingCreditsTotal),oper=operTotal/Math.max(1,a.monthsCovered),warnings=a.warnings.slice(),old=vfcBiqNumber_(base.averageMonthlyDeposits);if(old>0&&gross>0&&Math.abs(old-gross)/gross>=.05)warnings.push('Average monthly deposits corrected from '+vfcBiqRound_(old,1)+' to '+vfcBiqRound_(gross,1)+' using reconciled statement totals.');return Object.assign({},base,{statementCount:a.rows.length,monthsCovered:a.monthsCovered,totalDeposits:vfcBiqRound_(a.totalDeposits,.01),averageMonthlyDeposits:vfcBiqRound_(gross,.01),totalWithdrawals:vfcBiqRound_(a.totalWithdrawals,.01),depositWithdrawalRatio:vfcBiqRound_(a.totalWithdrawals?a.totalDeposits/a.totalWithdrawals:0,.01),nsfCount:a.nsfCount,nsfPerMonth:vfcBiqRound_(a.nsfCount/Math.max(1,a.monthsCovered),.01),negativeBalanceFlag:a.negativeBalanceFlag,mcaPaymentFlag:d.activeDebtObligations.length?1:0,monthlyDeposits:a.monthlyDeposits,monthlyWithdrawals:a.monthlyWithdrawals,depositVolatility:vfcBiqRound_(vfcBiqCoefficientOfVariation_(a.monthlyDeposits),.01),depositTrend:vfcBiqRound_(vfcBiqTrend_(a.monthlyDeposits),.01),estimatedOperatingTotalDeposits:vfcBiqRound_(operTotal,.01),estimatedOperatingMonthlyDeposits:vfcBiqRound_(oper,.01),detectedFinancingCredits:vfcBiqRound_(d.financingCreditsTotal,.01),existingMonthlyDebtService:vfcBiqRound_(d.confirmedMonthlyDebtService,.01),otherRecurringMonthlyObligations:0,informationalRecurringMonthlyObligations:vfcBiqRound_(d.informationalMonthlyObligations,.01),debtServiceToDepositsRatio:gross>0?vfcBiqRound_(d.confirmedMonthlyDebtService/gross,.0001):0,debtProfile:d,inputQualityAudit:{modelVersion:VFC_BANKING_INPUT_CONFIG.MODEL_VERSION,verified:true,selectedStatementRows:a.rows.length,validatedMonthsCovered:a.monthsCovered,grossAverageMonthlyDeposits:vfcBiqRound_(gross,.01),estimatedOperatingMonthlyDeposits:vfcBiqRound_(oper,.01),statementAudit:a.statementAudit,warnings:warnings}});}

function vfcBiqRefresh_(companyName,period){const rows=vfcBiqSelectedRows_(companyName,period);if(!rows.length)throw new Error('No current bank-statement rows were selected.');const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('PDF Summaries');if(!sh)throw new Error('Missing PDF Summaries sheet.');const up=vfcBiqUploadMap_(),reuse=vfcBiqReusablePayloadMap_(vfcBiqReadSummaryRows_(companyName,''));let analyzed=0,reused=0,skipped=0;const errors=[];rows.forEach(function(row,i){const cur=vfcBiqParsePayload_(row.possibleMcaOrLoanPayments),needDebt=i>=Math.max(0,rows.length-VFC_BANKING_INPUT_CONFIG.DEBT_LOOKBACK_STATEMENTS);if(cur&&cur.inputVerified&&cur.version>=VFC_BANKING_INPUT_CONFIG.PAYLOAD_VERSION&&vfcBiqPayloadTotalsVerified_(cur)){skipped++;return;}const prior=reuse[vfcBiqStatementIdentity_(row)];if(prior&&prior.inputVerified&&vfcBiqPayloadTotalsVerified_(prior)){vfcBiqWritePayload_(sh,row,vfcBiqMigratePayload_(prior,row,needDebt));reused++;return;}try{const stored=vfcBiqStoredTotals_(row);if(stored.verified&&!needDebt){vfcBiqWritePayload_(sh,row,vfcBiqCreatePayload_(row,vfcBiqBankKey_(row.bankName),'STORED_TOTALS_RECONCILED',stored,vfcBiqNumber_(row.nsfCount),[],[]));analyzed++;return;}const f=up[String(row.uploadId||'')]||{};if(!f.fileId)throw new Error('upload file ID not found');const text=extractTextFromPdf_(f.fileId);vfcBiqWritePayload_(sh,row,vfcBiqAnalyzeStatement_(text,row,stored,needDebt));analyzed++;}catch(e){errors.push(row.fileName+': '+String(e&&e.message||e));}});let a=vfcBiqBuildAudit_(companyName,period);if(!a.allStatementsVerified||a.processedRows!==a.rows.length){const repair=vfcBiqRepairUnverified_(companyName,period,a.rows);analyzed+=repair.filesAnalyzed;errors.push.apply(errors,repair.errors);a=vfcBiqBuildAudit_(companyName,period);}const incomplete=!a.allStatementsVerified||a.processedRows!==a.rows.length;if(incomplete&&a.unverifiedFiles.length)errors.push('Unverified statement(s): '+a.unverifiedFiles.join(', '));let features=null;if(!incomplete){try{features=getValidatedBankingFeatures_(companyName,period);}catch(e){errors.push(String(e&&e.message||e));}}return{ok:!incomplete&&errors.length===0,modelVersion:VFC_BANKING_INPUT_CONFIG.MODEL_VERSION,companyName:companyName,period:period,filesAnalyzed:analyzed,filesReused:reused,filesSkipped:skipped,errors:errors,statementAudit:a.statementAudit||[],debtProfile:features&&features.debtProfile?features.debtProfile:{},inputQualityAudit:features&&features.inputQualityAudit?features.inputQualityAudit:{unverifiedFiles:a.unverifiedFiles||[]}};}

function vfcBiqRepairUnverified_(companyName,period,rows){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('PDF Summaries'),up=vfcBiqUploadMap_();let n=0;const errors=[];(rows||vfcBiqSelectedRows_(companyName,period)).forEach(function(row,i){const p=vfcBiqParsePayload_(row.possibleMcaOrLoanPayments);if(p&&p.inputVerified&&p.version>=VFC_BANKING_INPUT_CONFIG.PAYLOAD_VERSION&&vfcBiqPayloadTotalsVerified_(p))return;try{const f=up[String(row.uploadId||'')]||{};if(!f.fileId)throw new Error('upload file ID not found');const text=extractTextFromPdf_(f.fileId),stored=vfcBiqStoredTotals_(row),need=i>=Math.max(0,rows.length-VFC_BANKING_INPUT_CONFIG.DEBT_LOOKBACK_STATEMENTS);vfcBiqWritePayload_(sh,row,vfcBiqAnalyzeStatement_(text,row,stored,need));n++;}catch(e){errors.push(row.fileName+': automatic repair failed - '+String(e&&e.message||e));}});return{filesAnalyzed:n,errors:errors};}

function vfcBiqAnalyzeStatement_(text,row,stored,needDebt){const bank=vfcBiqDetectBank_(text,row);let totals=null,method='';if(bank==='TD'){totals=vfcBiqParseTdTotals_(text,row);if(totals.verified)method='TD_PAGE_TOTALS_RECONCILED';}if((!totals||!totals.verified)&&stored&&stored.verified){totals=stored;method='STORED_TOTALS_RECONCILED';}if(!totals||!totals.verified){totals=vfcBiqExtractAndReconcileTotalsWithOpenAI_(text,row,bank);method='GENERIC_AI_TOTALS_RECONCILED';}if(!totals||!totals.verified)throw new Error('statement totals could not be reconciled'+(totals&&totals.reason?' ('+totals.reason+')':''));let pay=[],credits=[],nsf=vfcBiqNumber_(row.nsfCount);if(needDebt){if(bank==='TD'){pay=vfcBiqParseTdCandidates_(text,row);nsf=vfcBiqCountTdNsf_(text);}else{const s=vfcBiqExtractGenericSignalsWithOpenAI_(text,row);pay=s.paymentCandidates;credits=s.financingCredits;}}return vfcBiqCreatePayload_(row,bank,method,totals,nsf,pay,credits);}
function vfcBiqCreatePayload_(row,bank,method,t,nsf,pay,credits){return{version:VFC_BANKING_INPUT_CONFIG.PAYLOAD_VERSION,analyzedAt:new Date().toISOString(),statementIdentity:vfcBiqStatementIdentity_(row),fileName:row.fileName,bankName:row.bankName||bank,bankAdapter:bank,method:method,inputVerified:true,headerSummary:{statementStartDate:t.statementStartDate,statementEndDate:t.statementEndDate,openingBalance:t.openingBalance,closingBalance:t.closingBalance,totalDeposits:t.totalDeposits,totalWithdrawals:t.totalWithdrawals,reconciliationDifference:t.reconciliationDifference,pageCreditSubtotals:t.pageCreditSubtotals||[],pageDebitSubtotals:t.pageDebitSubtotals||[]},nsfCount:nsf,paymentCandidates:vfcBiqDedupeSignals_(pay||[]),financingCredits:vfcBiqFilterFinancingCredits_(credits||[])};}
function vfcBiqMigratePayload_(p,row,need){const t=vfcBiqReconcileTotals_(p.headerSummary||{});return vfcBiqCreatePayload_(row,p.bankAdapter||vfcBiqBankKey_(p.bankName||row.bankName),'REUSED_VERIFIED_PRIOR',t,vfcBiqNumber_(p.nsfCount),need?(p.paymentCandidates||[]):[],need?(p.financingCredits||[]):[]);}
function vfcBiqWritePayload_(sh,row,p){sh.getRange(row.rowNumber,row.signalColumn).setValue(VFC_BANKING_INPUT_CONFIG.SIGNAL_PREFIX+JSON.stringify(p));}
function vfcBiqPayloadTotalsVerified_(p){return!!(p&&p.headerSummary&&vfcBiqReconcileTotals_(p.headerSummary).verified);}
function vfcBiqStoredTotals_(row){return vfcBiqReconcileTotals_({statementStartDate:row.statementStartDate,statementEndDate:row.statementEndDate,openingBalance:row.openingBalance,closingBalance:row.closingBalance,totalDeposits:row.totalDeposits,totalWithdrawals:row.totalWithdrawals});}

function vfcBiqDetectBank_(text,row){const s=(String(row.bankName||'')+'\n'+String(text||'').substring(0,8000)).toUpperCase();if(/TD CANADA TRUST|TORONTO[- ]DOMINION|THE TORONTO-DOMINION BANK/.test(s))return'TD';if(/ROYAL BANK OF CANADA|\bRBC\b/.test(s))return'RBC';if(/BANK OF MONTREAL|\bBMO\b/.test(s))return'BMO';if(/SCOTIABANK|BANK OF NOVA SCOTIA/.test(s))return'SCOTIA';if(/CIBC|CANADIAN IMPERIAL BANK OF COMMERCE/.test(s))return'CIBC';if(/ATB FINANCIAL/.test(s))return'ATB';if(/NATIONAL BANK OF CANADA|BANQUE NATIONALE/.test(s))return'NBC';return'GENERIC';}
function vfcBiqBankKey_(v){const s=String(v||'').toUpperCase();if(/TD|TORONTO[- ]DOMINION/.test(s))return'TD';if(/RBC|ROYAL BANK/.test(s))return'RBC';if(/BMO|BANK OF MONTREAL/.test(s))return'BMO';if(/SCOTIA|NOVA SCOTIA/.test(s))return'SCOTIA';if(/CIBC|CANADIAN IMPERIAL/.test(s))return'CIBC';if(/ATB/.test(s))return'ATB';if(/NATIONAL BANK|BANQUE NATIONALE/.test(s))return'NBC';return s.replace(/[^A-Z0-9]/g,'').substring(0,24)||'GENERIC';}

function vfcBiqParseTdTotals_(text,row){const c=vfcBiqRegexMoneyValues_(text,/\bCredits\s+\d+\s+\$?\s*([0-9][0-9,]*\.\d{2})/gi),d=vfcBiqRegexMoneyValues_(text,/\bDebits\s+\d+\s+\$?\s*([0-9][0-9,]*\.\d{2})/gi);if(!c.length||!d.length)return{verified:false,reason:'TD page subtotals not found'};const dep=vfcBiqSum_(c),wd=vfcBiqSum_(d),b=vfcBiqParseTdOpeningClosingFromText_(text),ro=vfcBiqNullableNumber_(row.openingBalance),rc=vfcBiqNullableNumber_(row.closingBalance),pairs=[];if(b.openingBalance!==null&&b.closingBalance!==null)pairs.push({opening:b.openingBalance,closing:b.closingBalance,source:'TD_TEXT_BALANCES'});if(ro!==null&&rc!==null)pairs.push({opening:ro,closing:rc,source:'STORED_BALANCES'});if(b.openingBalance!==null&&rc!==null)pairs.push({opening:b.openingBalance,closing:rc,source:'TD_TEXT_OPEN_STORED_CLOSE'});if(ro!==null&&b.closingBalance!==null)pairs.push({opening:ro,closing:b.closingBalance,source:'STORED_OPEN_TD_TEXT_CLOSE'});if(!pairs.length)return{verified:false,reason:'TD opening/closing balance not found'};let best=null;for(let i=0;i<pairs.length;i++){const x=pairs[i],diff=Math.abs(x.opening+dep-wd-x.closing);if(!best||diff<best.diff)best={opening:x.opening,closing:x.closing,source:x.source,diff:diff};}if(!best||best.diff>VFC_BANKING_INPUT_CONFIG.RECONCILE_TOLERANCE_DOLLARS)return{verified:false,reason:'TD page totals found but no balance anchor pair reconciles; closest difference $'+vfcBiqRound_(best?best.diff:0,.01)};const out=vfcBiqReconcileTotals_({statementStartDate:row.statementStartDate,statementEndDate:row.statementEndDate,openingBalance:best.opening,closingBalance:best.closing,totalDeposits:dep,totalWithdrawals:wd,pageCreditSubtotals:c,pageDebitSubtotals:d});if(out.verified)out.balanceAnchorSource=best.source;return out;}
function vfcBiqParseTdOpeningClosingFromText_(text){const lines=String(text||'').split(/\r?\n/);let o=null,c=null;lines.forEach(function(raw){const line=String(raw||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();if(!line)return;if(o===null&&/BALANCE\s+FORWARD/i.test(line)){const m=line.match(/BALANCE\s+FORWARD\s+[A-Z]{3}\s*\d{1,2}\s+([0-9,]+\.\d{2})(OD)?/i);if(m){o=vfcBiqNumber_(m[1]);if(m[2])o=-Math.abs(o);}}const dm=line.match(/\b(?:JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|SEPT|OCT|NOV|DEC)\s*\d{1,2}\b/i);if(dm){const t=line.substring((dm.index||0)+dm[0].length).match(/([0-9,]+\.\d{2})(OD)?\s*$/);if(t){c=vfcBiqNumber_(t[1]);if(t[2])c=-Math.abs(c);}}});return{openingBalance:o,closingBalance:c};}
function vfcBiqExtractAndReconcileTotalsWithOpenAI_(text,row,bank){if(typeof callOpenAIJson_!=='function')return{verified:false,reason:'OpenAI JSON helper unavailable'};const prompt=['You are a bank-statement totals extractor. Return JSON only.','Bank hint: '+bank+'.','Extract only figures explicitly printed on the statement. Never estimate.','Return statement_start_date, statement_end_date, opening_balance, closing_balance, total_deposits, total_withdrawals, page_credit_subtotals, page_debit_subtotals.','If page subtotals exist, return ALL of them. Do not use monthly average balance, minimum balance, transaction amounts or running balances as totals.','Known period: '+String(row.statementStartDate||'')+' to '+String(row.statementEndDate||''),'OCR TEXT:',String(text||'').substring(0,60000)].join('\n');const r=callOpenAIJson_(prompt)||{},credits=vfcBiqNumberArray_(r.page_credit_subtotals),debits=vfcBiqNumberArray_(r.page_debit_subtotals);let dep=vfcBiqNullablePositiveNumber_(r.total_deposits),wd=vfcBiqNullablePositiveNumber_(r.total_withdrawals);if((dep===null||dep===0)&&credits.length)dep=vfcBiqSum_(credits);if((wd===null||wd===0)&&debits.length)wd=vfcBiqSum_(debits);return vfcBiqReconcileTotals_({statementStartDate:r.statement_start_date||row.statementStartDate,statementEndDate:r.statement_end_date||row.statementEndDate,openingBalance:r.opening_balance!==undefined?r.opening_balance:row.openingBalance,closingBalance:r.closing_balance!==undefined?r.closing_balance:row.closingBalance,totalDeposits:dep,totalWithdrawals:wd,pageCreditSubtotals:credits,pageDebitSubtotals:debits});}
function vfcBiqReconcileTotals_(x){const o=vfcBiqNullableNumber_(x&&x.openingBalance),c=vfcBiqNullableNumber_(x&&x.closingBalance),d=vfcBiqNullablePositiveNumber_(x&&x.totalDeposits),w=vfcBiqNullablePositiveNumber_(x&&x.totalWithdrawals);if(o===null||c===null||d===null||w===null)return{verified:false,reason:'all four balance fields are required'};const diff=Math.abs(o+d-w-c);if(diff>VFC_BANKING_INPUT_CONFIG.RECONCILE_TOLERANCE_DOLLARS)return{verified:false,reason:'balance reconciliation differs by $'+vfcBiqRound_(diff,.01)};return{verified:true,statementStartDate:vfcBiqIsoDate_(x.statementStartDate),statementEndDate:vfcBiqIsoDate_(x.statementEndDate),openingBalance:vfcBiqRound_(o,.01),closingBalance:vfcBiqRound_(c,.01),totalDeposits:vfcBiqRound_(d,.01),totalWithdrawals:vfcBiqRound_(w,.01),reconciliationDifference:vfcBiqRound_(diff,.01),pageCreditSubtotals:x.pageCreditSubtotals||[],pageDebitSubtotals:x.pageDebitSubtotals||[]};}

function vfcBiqParseTdCandidates_(text,row){const out=[],start=vfcBiqDate_(row.statementStartDate),end=vfcBiqDate_(row.statementEndDate);String(text||'').split(/\r?\n/).forEach(function(raw){const line=String(raw||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();if(!line||/BALANCE FORWARD|MONTHLY AVER|MONTHLY MIN|NEXT STATEMENT|\bCredits\b|\bDebits\b/i.test(line))return;const dm=line.match(/\b(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|SEPT|OCT|NOV|DEC)\s*([0-3]?\d)\b/i);if(!dm)return;const prefix=line.substring(0,dm.index||0).trim(),money=[];let m,re=/([0-9][0-9,]*\.\d{2})/g;while((m=re.exec(prefix))!==null)money.push({value:m[1],index:m.index});if(!money.length)return;const t=money[money.length-1],amount=vfcBiqPositiveNumber_(t.value),desc=prefix.substring(0,t.index).trim().replace(/^[-|\s]+/,'').replace(/\s+/g,' '),cat=vfcBiqClassifyTransactionDescription_(desc,amount),date=vfcBiqResolveTransactionDate_(dm[1],dm[2],start,end);if(desc&&amount>0&&cat&&date)out.push({date:vfcBiqIsoDate_(date),description:desc.substring(0,160),counterparty:desc.substring(0,100),amount:vfcBiqRound_(amount,.01),category:cat,confidence:cat==='OTHER_RECURRING'?'Moderate':'High'});});return out;}
function vfcBiqClassifyTransactionDescription_(d,amount){const s=String(d||'').toUpperCase();if(/\bFEE\b|SERVICE\s+CHRG|SERVICE\s+CHARGE|MONTHLY\s+PLAN|NSF|RETURN\s+FEE|PAYMENT\s+COVERAGE/i.test(s))return'';if(/\bCRA\b|\bCCRA\b|GST-P|\bGST\b|\bHST\b|SOURCE\s+D|\bTAX\b|\bWCB\b|\bEMPTX\b|\bTXBAL\b/i.test(s))return'TAX_GOVERNMENT';if(/\bIPFS\b|PREMIUM\s+FIN|INSURANCE\s+FIN|\bINSURANCE\b/i.test(s))return'INSURANCE_FINANCE';if(/CREDIT\s+CARD\s+PAYMENT|C\/C\s+PAYMENT/i.test(s))return'CREDIT_CARD';if(/\bMCA\b|MERCHANT\s+CASH\s+ADVANCE/i.test(s))return'MCA';if(/TRUCK\s*FIN|TRUCKFIN/i.test(s))return'TRUCK_FINANCE';if(/\bAUTO\s+FIN|\bVEHICLE\s+FIN|FORD\s+CREDIT|CREDIT\s+CA\s+(?:APY|PAY|PAA)/i.test(s))return'AUTO_FINANCE';if(/\bLINE\s+OF\s+CREDIT\b|\bLOC\b/i.test(s))return'LOC';if(/\bLEASE\b/i.test(s))return'LEASE_FINANCE';if(/\bLOAN\b|LOAN\s+PYMT|LOAN\s+PAYMENT/i.test(s))return'TERM_LOAN';if(/\bFINANC(?:E|IAL|ING)\b/i.test(s))return'OTHER_FINANCING_PAYMENT';if(/\bPAD\b|PRE[- ]?AUTH(?:ORIZED)?|PREAUTHORIZED/i.test(s))return amount>=50?'RECURRING_PAD':'';if(/\bRLS\b|\bBUS\b\s*$/i.test(s))return'OTHER_RECURRING';return'';}
function vfcBiqCountTdNsf_(text){const m=String(text||'').match(/\bNSF\s+(?:PAID|RETURN|RETURNED)?\s*FEE\b/gi);return m?m.length:0;}

function vfcBiqExtractGenericSignalsWithOpenAI_(text,row){if(typeof callOpenAIJson_!=='function')return{paymentCandidates:[],financingCredits:[]};const p=['You are a bank-statement transaction extractor. Return JSON only.','Extract each exact debit clearly identified as loan, financing, MCA, lease/LOC, PAD/pre-authorized debit, tax/government PAD, insurance finance or credit-card payment.','Do not decide recurrence. Never use a nearby amount. Fees, suppliers, payroll, purchases and ordinary transfers are not financing debt.','Also extract incoming financing credits only when explicitly identified as loan/funding/financing/cash-advance proceeds.','Return {payment_candidates:[{date,description,counterparty,amount,kind,confidence}], financing_credits:[{date,description,counterparty,amount,kind,confidence}]}.','Allowed payment kinds: LOAN_PAYMENT, MCA_PAYMENT, FINANCING_PAYMENT, PAD, TAX_PAD, INSURANCE_FINANCE, CREDIT_CARD_PAYMENT.','Allowed credit kinds: LOAN_ADVANCE, MCA_ADVANCE, OTHER_FINANCING_CREDIT.','Statement period: '+String(row.statementStartDate||'')+' to '+String(row.statementEndDate||''),'OCR TEXT:',String(text||'').substring(0,60000)].join('\n');const r=callOpenAIJson_(p)||{};return{paymentCandidates:vfcBiqNormalizeGenericPayments_(r.payment_candidates),financingCredits:vfcBiqNormalizeGenericCredits_(r.financing_credits)};}
function vfcBiqNormalizeGenericPayments_(a){if(!Array.isArray(a))return[];const map={LOAN_PAYMENT:'TERM_LOAN',MCA_PAYMENT:'MCA',FINANCING_PAYMENT:'OTHER_FINANCING_PAYMENT',PAD:'RECURRING_PAD',TAX_PAD:'TAX_GOVERNMENT',INSURANCE_FINANCE:'INSURANCE_FINANCE',CREDIT_CARD_PAYMENT:'CREDIT_CARD'};return a.map(function(x){x=x||{};const k=String(x.kind||'').toUpperCase().replace(/[^A-Z0-9]+/g,'_'),amt=vfcBiqPositiveNumber_(x.amount),desc=String(x.description||x.counterparty||'').trim();if(!map[k]||amt<=0||/\bFEE\b|SERVICE\s+CHARGE|NSF|PAYMENT\s+COVERAGE/i.test(desc))return null;return{date:vfcBiqIsoDate_(x.date),description:desc.substring(0,160),counterparty:String(x.counterparty||desc).trim().substring(0,100),amount:vfcBiqRound_(amt,.01),category:vfcBiqClassifyTransactionDescription_(desc,amt)||map[k],confidence:vfcBiqConfidence_(x.confidence)};}).filter(Boolean);}
function vfcBiqNormalizeGenericCredits_(a){if(!Array.isArray(a))return[];const ok={LOAN_ADVANCE:1,MCA_ADVANCE:1,OTHER_FINANCING_CREDIT:1};return a.map(function(x){x=x||{};const k=String(x.kind||'').toUpperCase().replace(/[^A-Z0-9]+/g,'_'),amt=vfcBiqPositiveNumber_(x.amount);if(!ok[k]||amt<5000||vfcBiqConfidence_(x.confidence)!=='High')return null;return{date:vfcBiqIsoDate_(x.date),description:String(x.description||'').trim().substring(0,160),counterparty:String(x.counterparty||x.description||'').trim().substring(0,100),amount:vfcBiqRound_(amt,.01),category:k,confidence:'High'};}).filter(Boolean);}
function vfcBiqFilterFinancingCredits_(a){return vfcBiqDedupeSignals_((a||[]).filter(function(x){return x&&vfcBiqPositiveNumber_(x.amount)>=5000&&x.confidence==='High';}));}

function vfcBiqBuildDebtProfile_(rows,months,latest){let pay=[],credits=[];(rows||[]).forEach(function(row){const p=vfcBiqParsePayload_(row.possibleMcaOrLoanPayments);if(p&&p.inputVerified){pay=pay.concat(p.paymentCandidates||[]);credits=credits.concat(p.financingCredits||[]);}});pay=vfcBiqDedupeSignals_(pay);credits=vfcBiqFilterFinancingCredits_(credits);const obs=vfcBiqGroupPayments_(pay).map(function(g){return vfcBiqSummarizeGroup_(g,months,latest);}).filter(Boolean).sort(function(a,b){return b.monthlyEquivalent-a.monthlyEquivalent;}),confirmed={TERM_LOAN:1,TRUCK_FINANCE:1,AUTO_FINANCE:1,COMMERCIAL_LOAN:1,LOC:1,LEASE_FINANCE:1,MCA:1,OTHER_FINANCING_PAYMENT:1,RECURRING_PAD:1},active=obs.filter(function(x){return x.active&&x.recurring&&confirmed[x.category]&&x.confidence!=='Low';}),tax=obs.filter(function(x){return x.active&&x.recurring&&x.category==='TAX_GOVERNMENT';}),other=obs.filter(function(x){return x.active&&x.recurring&&!confirmed[x.category]&&x.category!=='TAX_GOVERNMENT';});return{confirmedMonthlyDebtService:vfcBiqRound_(active.reduce(function(s,x){return s+x.monthlyEquivalent;},0),.01),otherRecurringMonthlyObligations:0,informationalMonthlyObligations:vfcBiqRound_(tax.concat(other).reduce(function(s,x){return s+x.monthlyEquivalent;},0),.01),activeDebtObligations:active,otherRecurringObligations:other,taxGovernmentPads:tax,observedOnce:obs.filter(function(x){return!x.recurring;}),allDetectedObligations:obs,financingCredits:credits,financingCreditsTotal:vfcBiqRound_(credits.reduce(function(s,x){return s+vfcBiqPositiveNumber_(x.amount);},0),.01),note:'Confirmed debt requires repeated explicit loan/finance/MCA/PAD transactions. Tax/government, insurance, cards and unclear recurring items are informational only. Fees are excluded.'};}
function vfcBiqGroupPayments_(a){const g={};(a||[]).forEach(function(x){if(!x||!x.date||vfcBiqPositiveNumber_(x.amount)<=0)return;const l=vfcBiqCanonicalLabel_(x);if(!l)return;const k=vfcBiqCategoryFamily_(x.category)+'|'+l;if(!g[k])g[k]={category:x.category,label:l,items:[]};g[k].items.push(x);});return Object.keys(g).map(function(k){return g[k];});}
function vfcBiqCategoryFamily_(c){return c==='TAX_GOVERNMENT'?c:c==='INSURANCE_FINANCE'?c:c==='CREDIT_CARD'?c:c==='OTHER_RECURRING'?c:'FINANCING';}
function vfcBiqCanonicalLabel_(x){const raw=String((x&&(x.counterparty||x.description))||'').toUpperCase();if(x&&x.category==='TAX_GOVERNMENT'){if(/\bCRA\b|\bCCRA\b/.test(raw))return'CRA CCRA TAX';if(/GST-P|\bGST\b|\bHST\b/.test(raw))return'GST HST TAX';if(/\bEMPTX\b/.test(raw))return'EMPLOYER TAX';if(/\bTXBAL\b/.test(raw))return'TAX BALANCE';if(/\bWCB\b/.test(raw))return'WCB';}return raw.replace(/\b(?:PAYMENT|PAYMENTS|PYMT|PMT|PAA|APY|MSP|PAD|PREAUTHORIZED|PRE-AUTHORIZED|DEBIT|WITHDRAWAL|EFT)\b/g,' ').replace(/\b\d{5,}\b/g,' ').replace(/[^A-Z0-9]+/g,' ').replace(/\s+/g,' ').trim().split(' ').slice(0,8).join(' ');}
function vfcBiqSummarizeGroup_(g,months,latest){if(!g||!g.items||!g.items.length)return null;const seen={};const a=g.items.filter(function(x){const k=vfcBiqIsoDate_(x.date)+'|'+vfcBiqRound_(x.amount,.01);if(!x.date||seen[k])return false;seen[k]=1;return true;}).sort(function(x,y){return(vfcBiqDate_(x.date)||new Date(0))-(vfcBiqDate_(y.date)||new Date(0));});if(!a.length)return null;const dates=a.map(function(x){return vfcBiqDate_(x.date);}).filter(Boolean),amounts=a.map(function(x){return vfcBiqPositiveNumber_(x.amount);}).filter(function(v){return v>0;}),n=dates.length,rec=n>=2,f=rec?vfcBiqInferFrequency_(dates,n,months):'Observed once',amt=vfcBiqMedian_(amounts),monthly=rec?vfcBiqMonthlyEquivalent_(amt,f,n,months):0,last=dates[dates.length-1];return{counterparty:vfcBiqBestCounterparty_(a),description:a[0].description||'',category:g.category,paymentAmount:vfcBiqRound_(amt,.01),frequency:f,monthlyEquivalent:vfcBiqRound_(monthly,.01),occurrences:n,firstSeen:vfcBiqIsoDate_(dates[0]),lastSeen:vfcBiqIsoDate_(last),recurring:rec,active:rec?vfcBiqIsActive_(last,latest,f):false,confidence:vfcBiqGroupConfidence_(a),patternLabel:g.label};}
function vfcBiqInferFrequency_(dates,n,months){if(dates&&dates.length>=2){const s=dates.slice().sort(function(a,b){return a-b;}),ints=[];for(let i=1;i<s.length;i++){const d=Math.abs((s[i]-s[i-1])/86400000);if(d>0)ints.push(d);}const d=vfcBiqMedian_(ints);if(d<=4)return'Business daily';if(d<=10)return'Weekly';if(d<=20)return'Biweekly';if(d<=45)return'Monthly';if(d<=75)return'Every 2 months';return'Irregular';}const p=n/Math.max(1,months||1);return p>=3?'Weekly':p>=1.5?'Biweekly':p>=.65?'Monthly':'Irregular';}
function vfcBiqMonthlyEquivalent_(a,f,n,m){a=vfcBiqPositiveNumber_(a);if(a<=0)return 0;if(f==='Business daily')return a*21.7;if(f==='Weekly')return a*4.33;if(f==='Biweekly')return a*2.17;if(f==='Monthly')return a;if(f==='Every 2 months')return a*.5;return a*Math.max(1,n)/Math.max(1,m||1);}
function vfcBiqIsActive_(last,latest,f){if(!last||!latest)return true;const days=(latest-last)/86400000,allow=f==='Every 2 months'?120:VFC_BANKING_INPUT_CONFIG.ACTIVE_LOOKBACK_DAYS;return days>=-3&&days<=allow;}
function vfcBiqBestCounterparty_(a){const c={};(a||[]).forEach(function(x){const t=String(x.counterparty||x.description||'').trim();if(t)c[t]=(c[t]||0)+1;});const k=Object.keys(c).sort(function(a,b){return c[b]!==c[a]?c[b]-c[a]:a.length-b.length;});return k.length?k[0]:'Recurring Payment';}
function vfcBiqGroupConfidence_(a){if(!a||!a.length)return'Low';const s=a.reduce(function(t,x){return t+(x.confidence==='High'?2:x.confidence==='Moderate'?1:0);},0)/a.length;return s>=1.5?'High':s>=.75?'Moderate':'Low';}

function vfcBiqBuildAudit_(companyName,period){const rows=vfcBiqSelectedRows_(companyName,period);let processed=0,ok=true,dep=0,wd=0,nsf=0,neg=0;const md=[],mw=[],audit=[],bad=[],ends=[];rows.forEach(function(row){const p=vfcBiqParsePayload_(row.possibleMcaOrLoanPayments);if(p)processed++;if(!p||!p.inputVerified||!vfcBiqPayloadTotalsVerified_(p)){ok=false;bad.push(row.fileName);return;}const h=p.headerSummary,d=vfcBiqPositiveNumber_(h.totalDeposits),w=vfcBiqPositiveNumber_(h.totalWithdrawals);dep+=d;wd+=w;md.push(d);mw.push(w);nsf+=Math.max(0,vfcBiqNumber_(p.nsfCount));if(vfcBiqTruthyFlag_(row.negativeBalanceDetected))neg=1;const e=vfcBiqDate_(h.statementEndDate||row.statementEndDate);if(e)ends.push(e);audit.push({fileName:row.fileName,bank:p.bankAdapter||p.bankName||'',statementStartDate:h.statementStartDate,statementEndDate:h.statementEndDate,totalDeposits:vfcBiqRound_(d,.01),totalWithdrawals:vfcBiqRound_(w,.01),method:p.method||'',reconciliationDifference:vfcBiqRound_(h.reconciliationDifference,.01),verified:true});});return{rows:rows,processedRows:processed,allStatementsVerified:ok,unverifiedFiles:bad,monthsCovered:rows.length,totalDeposits:dep,totalWithdrawals:wd,nsfCount:nsf,negativeBalanceFlag:neg,monthlyDeposits:md,monthlyWithdrawals:mw,latestStatementDate:ends.length?new Date(Math.max.apply(null,ends.map(function(d){return d.getTime();}))):null,statementAudit:audit,warnings:[]};}
function vfcBiqSelectedRows_(c,p){const a=vfcBiqReadSummaryRows_(c,p);return a.length?vfcBiqCurrentStatementWindow_(vfcBiqLatestBatch_(a)):[];}
function vfcBiqLatestBatch_(rows){const s=(rows||[]).slice().sort(function(a,b){return vfcBiqTime_(a.createdAt)-vfcBiqTime_(b.createdAt);});if(!s.length)return[];const out=[s[s.length-1]];let last=vfcBiqTime_(s[s.length-1].createdAt);for(let i=s.length-2;i>=0;i--){const t=vfcBiqTime_(s[i].createdAt);if(last&&t&&Math.abs(last-t)/60000>VFC_BANKING_INPUT_CONFIG.LATEST_BATCH_GAP_MINUTES)break;out.push(s[i]);if(t)last=t;}return out.reverse();}
function vfcBiqCurrentStatementWindow_(rows){const u=vfcBiqUniqueStatementRows_(rows).sort(function(a,b){return vfcBiqEffectiveDate_(a)-vfcBiqEffectiveDate_(b);}),out=[];let later=null;for(let i=u.length-1;i>=0;i--){const r=u[i],st=vfcBiqDate_(r.statementStartDate),en=vfcBiqDate_(r.statementEndDate)||st;if(out.length&&later&&en&&(later-en)/86400000>VFC_BANKING_INPUT_CONFIG.MAX_STATEMENT_GAP_DAYS)break;out.push(r);if(st)later=st;if(out.length>=VFC_BANKING_INPUT_CONFIG.MAX_STATEMENTS)break;}return out.reverse();}
function vfcBiqUniqueStatementRows_(rows){const m={};(rows||[]).forEach(function(r){const st=vfcBiqIsoDate_(r.statementStartDate),en=vfcBiqIsoDate_(r.statementEndDate),k=st&&en?st+'|'+en:String(r.fileName||'').toLowerCase(),e=m[k];if(!e||vfcBiqTime_(r.createdAt)>=vfcBiqTime_(e.createdAt))m[k]=r;});return Object.keys(m).map(function(k){return m[k];});}
function vfcBiqReusablePayloadMap_(rows){const m={};(rows||[]).forEach(function(r){const p=vfcBiqParsePayload_(r.possibleMcaOrLoanPayments);if(!p||!p.inputVerified||!vfcBiqPayloadTotalsVerified_(p))return;const k=p.statementIdentity||vfcBiqStatementIdentity_(r);if(!m[k]||p.version>m[k].version)m[k]=p;});return m;}
function vfcBiqStatementIdentity_(r){return[vfcBiqBankKey_(r.bankName),String(r.companyName||'').trim().toLowerCase(),vfcBiqIsoDate_(r.statementStartDate),vfcBiqIsoDate_(r.statementEndDate)].join('|');}

function vfcBiqReadSummaryRows_(companyName,period){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('PDF Summaries');if(!sh)return[];const v=sh.getDataRange().getValues();if(v.length<2)return[];const h=v[0],c={u:vfcBiqColumn_(h,'Upload ID'),co:vfcBiqColumn_(h,'Company Name'),p:vfcBiqColumn_(h,'Detected Period'),f:vfcBiqColumn_(h,'File Name'),b:vfcBiqColumnOptional_(h,'Bank Name'),s:vfcBiqColumn_(h,'Statement Start Date'),e:vfcBiqColumn_(h,'Statement End Date'),o:vfcBiqColumnOptional_(h,'Opening Balance'),cl:vfcBiqColumnOptional_(h,'Closing Balance'),d:vfcBiqColumn_(h,'Total Deposits'),w:vfcBiqColumn_(h,'Total Withdrawals'),n:vfcBiqColumn_(h,'NSF Count'),ng:vfcBiqColumn_(h,'Negative Balance Detected'),sig:vfcBiqColumn_(h,'Possible MCA Or Loan Payments'),cr:vfcBiqColumn_(h,'Created At')};return v.slice(1).map(function(r,i){return{uploadId:r[c.u],companyName:r[c.co],detectedPeriod:r[c.p],fileName:String(r[c.f]||'statement.pdf'),bankName:c.b>=0?r[c.b]:'',statementStartDate:r[c.s],statementEndDate:r[c.e],openingBalance:c.o>=0?r[c.o]:'',closingBalance:c.cl>=0?r[c.cl]:'',totalDeposits:r[c.d],totalWithdrawals:r[c.w],nsfCount:r[c.n],negativeBalanceDetected:r[c.ng],possibleMcaOrLoanPayments:r[c.sig],createdAt:r[c.cr],rowNumber:i+2,signalColumn:c.sig+1};}).filter(function(r){return(!companyName||vfcBiqSame_(r.companyName,companyName))&&(!period||vfcBiqSame_(r.detectedPeriod,period));});}
function vfcBiqUploadMap_(){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Uploads');if(!sh)return{};const v=sh.getDataRange().getValues();if(v.length<2)return{};const h=v[0],u=vfcBiqColumn_(h,'Upload ID'),f=vfcBiqColumn_(h,'File ID'),m={};v.slice(1).forEach(function(r){const id=String(r[u]||'').trim();if(id)m[id]={fileId:String(r[f]||'').trim()};});return m;}
function vfcBiqParsePayload_(value){const t=String(value||'').trim();let pre='';for(let i=0;i<VFC_BANKING_INPUT_CONFIG.LEGACY_PREFIXES.length;i++){if(t.indexOf(VFC_BANKING_INPUT_CONFIG.LEGACY_PREFIXES[i])===0){pre=VFC_BANKING_INPUT_CONFIG.LEGACY_PREFIXES[i];break;}}if(!pre)return null;try{const p=JSON.parse(t.substring(pre.length));return{version:vfcBiqNumber_(p.version),analyzedAt:p.analyzedAt||'',statementIdentity:p.statementIdentity||'',fileName:p.fileName||'',bankName:p.bankName||'',bankAdapter:p.bankAdapter||'',method:p.method||'',inputVerified:!!p.inputVerified,headerSummary:p.headerSummary||{},nsfCount:vfcBiqNumber_(p.nsfCount),paymentCandidates:Array.isArray(p.paymentCandidates)?p.paymentCandidates:[],financingCredits:Array.isArray(p.financingCredits)?p.financingCredits:[]};}catch(e){return null;}}

function vfcBiqEffectiveDate_(r){const p=vfcBiqParsePayload_(r.possibleMcaOrLoanPayments),h=p&&p.headerSummary?p.headerSummary:{};return vfcBiqDate_(h.statementEndDate||r.statementEndDate||h.statementStartDate||r.statementStartDate)||new Date(0);}
function vfcBiqDedupeSignals_(a){const s={};return(a||[]).filter(function(x){if(!x)return false;const k=[vfcBiqIsoDate_(x.date),vfcBiqRound_(vfcBiqPositiveNumber_(x.amount),.01),String(x.category||''),vfcBiqCanonicalLabel_(x)].join('|').toLowerCase();if(!x.date||!x.category||s[k])return false;s[k]=1;return true;});}
function vfcBiqResolveTransactionDate_(m,d,st,en){const months={JAN:0,FEB:1,MAR:2,APR:3,MAY:4,JUN:5,JUL:6,AUG:7,SEP:8,SEPT:8,OCT:9,NOV:10,DEC:11},mo=months[String(m||'').toUpperCase()],day=parseInt(d,10);if(mo===undefined||day<1||day>31)return null;const ys=[];if(st)ys.push(st.getUTCFullYear());if(en&&ys.indexOf(en.getUTCFullYear())<0)ys.push(en.getUTCFullYear());let best=null,dist=Infinity;ys.forEach(function(y){const x=new Date(Date.UTC(y,mo,day)),a=en||st||new Date(),dd=Math.abs(x-a),inside=(!st||x>=new Date(st.getTime()-3*86400000))&&(!en||x<=new Date(en.getTime()+3*86400000));if(inside&&dd<dist){best=x;dist=dd;}});return best;}
function vfcBiqRegexMoneyValues_(t,re){const a=[];let m;while((m=re.exec(String(t||'')))!==null)a.push(vfcBiqPositiveNumber_(m[1]));return a;}
function vfcBiqNumberArray_(v){return Array.isArray(v)?v.map(vfcBiqPositiveNumber_).filter(function(n){return n>=0;}):[];}
function vfcBiqColumn_(h,w){const i=vfcBiqColumnOptional_(h,w);if(i>=0)return i;throw new Error('Missing required column: '+w);}
function vfcBiqColumnOptional_(h,w){const t=String(w||'').toLowerCase().replace(/[^a-z0-9]/g,'');for(let i=0;i<h.length;i++)if(String(h[i]||'').toLowerCase().replace(/[^a-z0-9]/g,'')===t)return i;return-1;}
function vfcBiqNormalizeRequest_(x,p){let c='',period=p||'';if(x&&typeof x==='object'){c=x.companyName||x.company||'';period=x.period||x.detectedPeriod||period;}else c=x||'';c=String(c||'').trim();period=String(period||'').trim();if(!c)throw new Error('Company name is required.');return{companyName:c,period:period};}
function vfcBiqConfidence_(v){const t=String(v||'').trim().toLowerCase();return t==='high'?'High':t==='low'?'Low':'Moderate';}
function vfcBiqDate_(v){if(!v)return null;const d=v instanceof Date?v:new Date(v);return isNaN(d.getTime())?null:d;}
function vfcBiqIsoDate_(v){const d=vfcBiqDate_(v);return d?Utilities.formatDate(d,'UTC','yyyy-MM-dd'):'';}
function vfcBiqNumber_(v){if(typeof v==='number')return isFinite(v)?v:0;const n=parseFloat(String(v||'').replace(/[^0-9.\-]/g,''));return isFinite(n)?n:0;}
function vfcBiqNullableNumber_(v){if(v===''||v===null||v===undefined)return null;const t=String(v).trim();if(!t)return null;let n=vfcBiqNumber_(t);if(/OD$/i.test(t))n=-Math.abs(n);return n;}
function vfcBiqNullablePositiveNumber_(v){if(v===''||v===null||v===undefined)return null;const t=String(v).trim();if(!t)return null;const n=vfcBiqNumber_(t);return isFinite(n)&&n>=0?n:null;}
function vfcBiqPositiveNumber_(v){return Math.max(0,vfcBiqNumber_(v));}
function vfcBiqTruthyFlag_(v){return/^(1|true|yes|detected)$/i.test(String(v||'').trim())?1:0;}
function vfcBiqRound_(v,s){const n=vfcBiqNumber_(v),i=vfcBiqNumber_(s)||1;return Math.round(n/i)*i;}
function vfcBiqSum_(a){return(a||[]).reduce(function(s,v){return s+vfcBiqNumber_(v);},0);}
function vfcBiqMedian_(a){const n=(a||[]).map(vfcBiqNumber_).filter(function(v){return v>0;}).sort(function(a,b){return a-b;});if(!n.length)return 0;const m=Math.floor(n.length/2);return n.length%2?n[m]:(n[m-1]+n[m])/2;}
function vfcBiqCoefficientOfVariation_(a){const n=(a||[]).map(vfcBiqNumber_).filter(function(v){return v>=0;});if(!n.length)return 1;const avg=vfcBiqSum_(n)/n.length;if(!avg)return 1;return Math.sqrt(n.reduce(function(s,v){return s+Math.pow(v-avg,2);},0)/n.length)/avg;}
function vfcBiqTrend_(a){const n=(a||[]).map(vfcBiqNumber_);if(n.length<2)return 0;const sp=Math.max(1,Math.floor(n.length/2)),f=n.slice(0,sp),s=n.slice(sp),fa=vfcBiqSum_(f)/f.length,sa=s.length?vfcBiqSum_(s)/s.length:fa;return fa>0?(sa-fa)/fa:0;}
function vfcBiqSame_(a,b){return String(a==null?'':a).trim().toLowerCase()===String(b==null?'':b).trim().toLowerCase();}
function vfcBiqTime_(v){const d=vfcBiqDate_(v);return d?d.getTime():0;}